### ISSUE TITLE
stickers for contributors

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#100]
If you've contributed to this repository I'd like to take this opportunity to thank you!

As a small gesture of appreciation, I'd like to mail you an esri-loader sticker if you're interested. I've got a handful left over from the 2018 DevSummit:

https://twitter.com/tomwayson/status/972167058606587904

If you weren't there or didn't get a chance to grab one, DM me on twitter w/ an address to send it to. If you don't think I'd be able to guess your GitHub username from your twitter handle, please include that as well, or a link to any PR/issue you've made.

Thanks again for all you do!

And yes, @davetimmins, for you, I will even mail to NZ.

**Comment by tomwayson** [comment]
I should have said contributed to this repository or any of the [example repos](https://github.com/Esri/esri-loader#examples).

First come, first serve, supplies are limited. ;)

**Comment by andygup** [comment]
Closing out since we are post DevSummit.
