### ISSUE TITLE
Uncaught (in promise) Error: The ArcGIS API for JavaScript is already loaded (https://js.arcgis.com/4.6/).

### ISSUE THREAD

**Issue by kgloveyou** [Esri/esri-loader#103]
I  wrote my code like this,
```
// preload the ArcGIS API
const options = {
	url: 'https://js.arcgis.com/3.23/',                        
};                    
loadScript(options);
```
when i refresh the page ,it throw an error in the console:
`Uncaught (in promise) Error: The ArcGIS API for JavaScript is already loaded (https://js.arcgis.com/4.6/).`

and the map page is blank.
How to resolve this problem?

ps： the esri-loader version is 2.2.0

**Comment by tomwayson** [comment]
can you provide more code? Are you using a `<script>` tag to load the API as well? Where are you calling `loadModules()`? Can you try w/o `loadScript()` and _just_ use `loadModules()`?

**Comment by kgloveyou** [comment]
I have written the code in bussiness vue page,it should be in the app.vue page.
