### ISSUE TITLE
routes between two points

### ISSUE THREAD

**Issue by bhumin3i** [Esri/esri-loader#110]
This is not a bug

Need some help on the below:

how to Display routes between two points using ionic 3/2 or angular 2

**Comment by andygup** [comment]
@bhumin3i questions related to Ionic are best asked over on the ionic2-esri-map repo: https://github.com/andygup/ionic2-esri-map/issues 

Once you have the hello world map app working you should be able to borrow code from this routing example: https://developers.arcgis.com/javascript/latest/sample-code/tasks-route/index.html 

Note: we focus on supporting the latest versions of Ionic and Angular.

For general ArcGIS JavaScript API questions please use: https://community.esri.com/community/developers/web-developers/arcgis-api-for-javascript

**Comment by bhumin3i** [comment]
thanks so much @andygup but I get some URL error while get routing data :(

for get data from ArcGis, I use 
```
// Proxy the route requests to avoid prompt for log in
       urlUtils.addProxyRule({
        urlPrefix: "route.arcgis.com",
        proxyUrl: "/sproxy/"
      });
       // Point the URL to a valid route service
       var routeTask = new RouteTask({
        url: "https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World"
      });
```

On **android devic**e in console I have seen some url error 

`file:///sproxy/?https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World/solve?f=json&returnDirections=false&returnRoutes=true&returnZ=true&returnStops=false&returnBarriers=false&returnPolygonBarriers=false&returnPolylineBarriers=false&outSR=3857&outputLines=esriNAOutputLineTrueShape&stops=%7B%22type%22%3A%22features%22%2C%22features%22%3A%5B%7B%22geometry%22%3A%7B%22spatialReference%22%3A%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D%2C%22x%22%3A8126553.915984148%2C%22y%22%3A2162956.3638093127%7D%2C%22attributes%22%3A%7B%7D%7D%2C%7B%22geometry%22%3A%7B%22spatialReference%22%3A%7B%22latestWkid%22%3A3857%2C%22wkid%22%3A102100%7D%2C%22x%22%3A8126518.645968654%2C%22y%22%3A2162365.1711686538%7D%2C%22attributes%22%3A%7B%7D%7D%5D%2C%22doNotLocateOnRestrictedElements%22%3Atrue%7D 0 ()`
