### ISSUE TITLE
Update for v4.8

### ISSUE THREAD

**Issue by davidpiesse** [Esri/esri-loader#120]
Can we get a new release that incorporates the most recent upgrades to the JS API (4.8 & 3.25)?

Thanks 💯

**Comment by tomwayson** [comment]
Pull requests are gladly accepted. 😉

**Comment by davidpiesse** [comment]
I'm on it!

**Comment by tomwayson** [comment]
FYI - this has been released in [v2.4.0](https://github.com/Esri/esri-loader/releases/tag/v2.4.0)
