### ISSUE TITLE
Standalone ArcGIS JS

### ISSUE THREAD

**Issue by DevChagrins** [Esri/esri-loader#126]
When passing an Options object to loadScript using a URL that is pointed at a standalone ArcGIS JS installation, I receive the following error:

> TypeError: Cannot read property 'on' of undefined

I'm using the npm package create-react-app version 1.1.4 and esri-loader version 2.4.0

The issue only occurs when I point to a local installation of ArcGIS JS. Removing the URL options or pointing it to https://js.arcgis.com/4.5/ or https://js.arcgis.com/4.8/ works without any problems.

### Steps to replicate

- npm install create-react-app and esri-loader
- Run npx create-react-app my-test-app
- Open the App.js that has been generated and replace it with the code below and point the options url to a local ArcGIS JS installation
- Make sure the dev server is running and visit localhost:3000, open the debug console for your browser

```import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import * as esriLoader from 'esri-loader';

class App extends Component {
  componentDidMount() {
    var options = {
      url: "http://localhost:13013/4.5/",
      dojoConfig: {
        async: true,
        baseUrl: "http://localhost:13013/4.5/dojo"
      }
    };
    // has the ArcGIS API been added to the page?
    if (!esriLoader.isLoaded()) {
      console.log("Is not Loaded");
      // no, lazy load it the ArcGIS API before using its classes
      esriLoader.loadModules(['esri/Map', 'esri/views/MapView'], options).then(([Map, MapView]) => { 
        console.log("Test");
        var map = new Map({
          basemap: "topo"
        });

        this.view = new MapView({
          container: this.mapContainer,
          map: map
        });
      });
    }
  }

  render() {
    return (
      <div className="App">
        <div style={{height:'100%'}} ref={node => this.mapContainer = node}/>
      </div>
    );
  }
}

export default App;
```

**Comment by tomwayson** [comment]
What does your network traffic in developer tools show for `http://localhost:13013/*`?

**Comment by DevChagrins** [comment]
I get a status 200. The localhost is on my personal machine that I did to separately test out what I could from our development environment. I use IIS on my laptop, but we use another system to serve ArcGIS JS. Both get the same error, but I know it works as we used it in another website we built using AngularJS.

**Comment by tomwayson** [comment]
Do the response bodies for those requests look good?

So the above `console.log("Test");` line executes? Can you log `Map, MapView` at that point?

Which line throws the error?

**Comment by davetimmins** [comment]
@DevChagrins I've used it with a local API using the full dojo.js file path for the url e.g.

```js
var options = {
      url: "http://localhost:13013/4.5/dojo/dojo.js"
    };
```

**Comment by tomwayson** [comment]
@DevChagrins 

FYI - now that you've got this working, you do not need the `if (!esriLoader.isLoaded()) {` check - that is handled for you in `loadModules()` now.
