### ISSUE TITLE
dojoConfig has bug when 'location' contains 'static'

### ISSUE THREAD

**Issue by chendb** [Esri/esri-loader#128]
### dojoConfig has bug when 'location' contains 'static'

1. this is my config 
```
        const options = {
            url: "https://js.arcgis.com/3.21/",
            dojoConfig: {
                async: true,
                packages: [
                    {
                        location: "http://localhost:8200/static/egova/mapv/",
                        name: "mapv"
                    }
                ]
            }
        };
           
```
2. load modules

```
loadModules(
            [
              ....

                "mapv/AnimationLayer",
                "mapv/CanvasLayer",
                "mapv/Layer",
...
            ] ).then(()=>{});
```

### issue
 I find ,send request is 'https://js.arcgis.com/3.21/egova/mapv/AnimationLayer.js'.
when I change config ,
```
       const options = {
            url: "https://js.arcgis.com/3.21/",
            dojoConfig: {
                async: true,
                packages: [
                    {
                        location: "http://localhost:8200/static1/egova/mapv/",
                        name: "mapv"
                    }
                ]
            }
        };
```

send request is  'http://localhost:8200/static1/egova/mapv/AnimationLayer.js'.

**Comment by tomwayson** [comment]
That is really odd.

Have you checked to see if this happens outside of esri-loader? I mean, can you copy [a simple sample page](https://developers.arcgis.com/javascript/3/jssamples/map_simple.html), add the first config above config, and then load those modules? Does that work?

**Comment by tomwayson** [comment]
@chendb I'm going to assume the workaround you suggest above is sufficient for you and close this issue. Feel free to re-open if needed.
