### ISSUE TITLE
Does not work for 3.25 version

### ISSUE THREAD

**Issue by slitvin** [Esri/esri-loader#133]
### Expected behavior

When I am trying  with 3.25 version(locally or remote) it does not work.
url: '//js.arcgis.com/3.25/'
environment: Windows 10
framework: Angular 5, CLI

### Actual behavior

- console error when loading modules
- not loaded
- init.js:36 GET https://js.arcgis.com/3.25/esri/Map.js net::ERR_ABORTED 404
g.injectUrl @ init.js:36
ra @ init.js:32
e @ init.js:10
(anonymous) @ init.js:19
ka @ init.js:28
oa @ init.js:19
Qa @ init.js:20
g @ init.js:11
dojoRequire @ esri-loader.js:221
(anonymous) @ esri-loader.service.js:41
ZoneAwarePromise @ zone.js:891
EsriLoaderService.loadModules @ esri-loader.service.js:40
(anonymous) @ app-esri-map.component.ts:29
ZoneDelegate.invoke @ zone.js:388
onInvoke @ core.js:4760
ZoneDelegate.invoke @ zone.js:387
Zone.run @ zone.js:138
(anonymous) @ zone.js:872
ZoneDelegate.invokeTask @ zone.js:421
onInvokeTask @ core.js:4751
ZoneDelegate.invokeTask @ zone.js:420
Zone.runTask @ zone.js:188
drainMicroTaskQueue @ zone.js:595
ZoneTask.invokeTask @ zone.js:500
invokeTask @ zone.js:1540
globalZoneAwareCallback @ zone.js:1566
error (async)
customScheduleGlobal @ zone.js:1666
ZoneDelegate.scheduleTask @ zone.js:407
Zone.scheduleTask @ zone.js:232
Zone.scheduleEventTask @ zone.js:258
(anonymous) @ zone.js:1831
Oa @ init.js:34
g.injectUrl @ init.js:35
ra @ init.js:32
e @ init.js:10
(anonymous) @ init.js:19
ka @ init.js:28
oa @ init.js:19
Qa @ init.js:20
b @ init.js:20
c @ init.js:1013
load @ init.js:1014
$a @ init.js:29
(anonymous) @ init.js:26
e @ init.js:10
mb @ init.js:26
ia @ init.js:27
ja @ init.js:28
(anonymous) @ init.js:29
ka @ init.js:28
ha @ init.js:28
Na @ init.js:33
Ma @ init.js:36
(anonymous) @ init.js:2640
init.js:37 Error: scriptError
    at c (init.js:11)
    at HTMLScriptElement.<anonymous> (init.js:35)
    at ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:4751)
    at ZoneDelegate.invokeTask (zone.js:420)
    at Zone.runTask (zone.js:188)
    at ZoneTask.invokeTask [as invoke] (zone.js:496)
    at invokeTask (zone.js:1540)
    at HTMLScriptElement.globalZoneAwareCallback (zone.js:1566)

### Steps to reproduce the behavior

**We can only help you if we're able to easily reproduce the behavior you describe above.**

Please provide:

 Steps to reproduce the behavior.
Angular code:
return this.esriLoader.load({
      // use a specific version of the API instead of the latest      
      url: '//js.arcgis.com/3.25/'
      //url: '../../../assets/arcgis_js_api/library/3.25/3.25/'
      //url: 'https://js.arcgis.com/4.7/'
      //url: '//makanak.arcgis/arcgis_js_api/library/3.25/3.25/'
    }).then(() => {
      console.log('step2');

**Comment by tomwayson** [comment]
I think you're trying to load `esri/Map` which does not exist in 3.x. It's only in [4.x](https://js.arcgis.com/4.8/esri/Map.js). 3.x has [esri/map](https://js.arcgis.com/3.25/esri/map.js).

Make sure your call to `loadModules()` only includes 3.x classes. In this case, the above error can be corrected by replacing `'esri/Map'` w/ `'esri/map'`.

**Comment by andygup** [comment]
And, here's a `3.25` example: https://github.com/Esri/angular-cli-esri-map/issues/17. I was using Angular 6, but it tested okay two weeks ago.

**Comment by tomwayson** [comment]
@slitvin I'm going to assume you were able to get this working and close this issue. Feel free to re-open if needed.
