### ISSUE TITLE
update README snippets to use ES2015 syntax

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#136]
The most common way people should use this library is to import the fns they need:

```js
import { loadModules } from 'esri-loader';

loadModules(...)
```

So I think it's better for the examples show that expected usage than to show `esriLoader.loadModules()`. The only reason they currently show that usage is b/c it works w/ both ES2015 (i.e. via `import esriLoader from 'esri-loader') _and_ ES5 (via the `esriLoader` global).

Maybe add a discrete ES5/CDN example that shows how to use the global.

At the next breaking change (3.0) I'd like to go so far as to drop the default export, so I want to start training people not to `import` it.

**Comment by jwasilgeo** [comment]
When I can make some time I'd be interested in working on this one, @tomwayson.  I'm curious ,if I end up working on this, do you have any strong feelings for or against async/await syntax vs. `then`?  Or do you want the main focus here to be on `import`?

**Comment by tomwayson** [comment]
Thanks @jwasilgeo - I think it's best to leave `async`/`await` out of it for now.
