### ISSUE TITLE
Handle script load errors

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#14]
As suggested by @davetimmins in https://github.com/tomwayson/esri-loader/pull/13#issuecomment-290962974

I've actually [implemented this in the ember version](https://github.com/Esri/ember-esri-loader/blob/c8688f547b3d8d63a85ce94f1985adc5e40b85bd/addon/services/esri-loader.js#L54-L56) and that could be used for reference.

**Comment by nicksenger** [comment]
Hi @tomwayson , can you provide an example of how one would handle script loading errors using `esriLoader.dojoRequire` without accessing window['require'] directly?

I see the `onScriptError` defined in `bootstrap`, but can't seem to figure out how/if that relates to `dojoRequire`

**Comment by davetimmins** [comment]
@nicksenger I think it assumes you've already called `bootstrap` and the onload in `dojoRequire` is just to be notified of the currently loading script, so if it errors you'd still get the error from the original `bootstrap` call

**Comment by tomwayson** [comment]
Correct @davetimmins and good point @nicksenger. I guess that is a bit of an oversight. If you don't use `bootstrap()` to load the script you won't necessarily have a way to handle the script loading errors.

A bigger issue is that `dojoRequire()` doesn't give you any way to handle _any_ errors, regardless of whether they happened while loading the script or the modules, the way that `esriPromise()` does. I'm about to push a branch that uses promises instead of callbacks, and basically is a wholesale rip off the `esriPromise()` API (and some of it's source code - thanks @nicksenger 😉). That will be a better solution to https://github.com/Esri/esri-loader/issues/14#issuecomment-343003784.

**Comment by andygup** [comment]
@tomwayson do you know of specific errors that would bubble? I haven't seen any yet, but haven't really tested for it. For example, "require not defined", or what would happen if a module fails with like a 504 error?

**Comment by tomwayson** [comment]
Well @andygup I've seen my share of module 404s through the years, mostly due to misconfigured `packages`.

The above issues will be handled in https://github.com/Esri/esri-loader/pull/48
