### ISSUE TITLE
issue requiring a module that loads other modules (wasm)

### ISSUE THREAD

**Issue by steveoh** [Esri/esri-loader#140]
### Expected behavior

- I want to be able to require and load the `esri/geometry/projection` engine
- I want to project some points on the client

```
  System:
    OS: macOS 10.14
    CPU: x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
  Binaries:
    Node: 8.12.0 - /usr/local/opt/node@8/bin/node
    npm: 6.4.1 - /usr/local/opt/node@8/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Firefox: 61.0
    Safari: 12.0
  npmPackages:
    react: ^16.5.2 => 16.5.2 
    react-dom: ^16.5.2 => 16.5.2 
    react-scripts: 2.0.5 => 2.0.5 
    esri-loader: ^2.5.0 => 2.5.0
  npmGlobalPackages:
    create-react-app: Not Found
```

### Actual behavior

- Describe what occurs in your code.

1. I import loadModules

    ```js
    import { loadModules } from 'esri-loader';
    ```

1. I request the projection engine

    ```js
    const [projection] = await loadModules(['esri/geometry/projection']);
    ```

1. The projection engine module has a [load method](https://developers.arcgis.com/javascript/3/jsapi/esri.geometry.projection-amd.html#load) that loads the wasm for the projection engine which returns a deferred.

    ```js
    await projection.load();
    ```

1. This, I think, is fouling up webpack looking for the wasm code instead of using the dojo loader as an error is thrown.

- Specifically, what seems to work differently than you intended?

When I `await` the `Deferred` on the `load` method, the methods on the object are not there. If I do some debugging and expand properties etc, eventually they show up but I don't know what causes that. 

- Provide any error messages you see in the console.

```
1.chunk.js:39115 ReferenceError: __WEBPACK_EXTERNAL_MODULE__2120__ is not defined
    at Object.<anonymous> (bundle.js:20)
    at n (bundle.js:1)
    at bundle.js:16
function.console.(anonymous function) @ 1.chunk.js:39115
14:31:24.420 bundle.js:20 Uncaught (in promise) ReferenceError: __WEBPACK_EXTERNAL_MODULE__2120__ is not defined
    at Object.<anonymous> (bundle.js:20)
    at n (bundle.js:1)
    at bundle.js:16
```

### Steps to reproduce the behavior

**We can only help you if we're able to easily reproduce the behavior you describe above.**

Please provide:

1. Steps to reproduce the behavior.
   Follow the steps above
 
2. A link to an app where we can carry out those steps (e.g. your publicly facing app, a JSFiddle, a JS Bin, etc.).
    [jsfiddle](https://jsfiddle.net/69z2wepo/316688/) - but this works... presumably because things are different between the fiddle and CRA? Now I'm wondering about the CRA node server etc and WASM
3. Relevant code snippet(s) (only if not easily obtained from the above link).

    Pretty sure they are also above

**Comment by steveoh** [comment]
omg. I still had 

```html
    <script type="text/javascript" src="https://cdn.jsdelivr.net/gh/g3r4n/arcgispack@0.0.25/esri-bundle/bundle.js"></script>
```
in my index file from the pack/wrapper thing, so the application wasn't using the 4x cdn.

**Comment by andygup** [comment]
oops, I won't tell anyone.
