### ISSUE TITLE
Dojo Error when loading the ArcGIS JavaScript API higher than 4.8 in a VueJS component

### ISSUE THREAD

**Issue by tommckennon** [Esri/esri-loader#144]
### Expected behavior

We have an application with the front-end built using the VueJs framework (version "2.5.17"). We are successfully using the esri-loader by pre-loading the ArcGIS JavaScript API at version 4.8, but a dojo error is occurring when attempting to load 4.9 or 4.10.

### Actual behavior

This is the dojo error that is occurring when pre-loading the ArcGIS JavaScript API at 4.9 or 4.10 using the latest esri-loader in a Vue component. 
Error:
dojo.js:438 Uncaught TypeError: Cannot read property 'fromCodePoint' of undefined
    at dojo.js:438
    at Array.every (<anonymous>)
    at dojo.js:438
    at Object.l [as default] (dojo.js:443)
    at dojo.js:447
    at N (dojo.js:19)
    at N (dojo.js:18)
    at N (dojo.js:18)
    at N (dojo.js:18)
    at N (dojo.js:18)
(anonymous)	@	dojo.js:438
...

### Steps to reproduce the behavior

This is how we are pre-loading the ArcGIS JavaScript API using the esri-loader and loading the JavaScript modules using the esri-loader. Again, it works for version 4.8, but not the more recent versions.

Vue component code:
`
```
<style>
@import url("https://js.arcgis.com/4.10/esri/css/main.css");
#esriMap {
  position: absolute;
  width: 100%;
  height: 650px;
}
</style>
<template>
  <div>
    <div id="esriMap"></div>
  </div>
</template>

<script>
import * as EsriLoader from "esri-loader";
import * as Api from "../api/contentApi";

export default {
  props: {
    mapData: null,
    enableWidgets: Boolean,
    mapFilters: null,
    activeLayerType: null
  },
  data() {
    return {
      appConfig: null,
      portalUrl: "https://maps.arcgis.com",
      arcgisApiMods: null,
      webMap: null,
      webMapView: null,
      webMapQueryLayers: [],
      mapLayerTypes: Object
    };
  },
  async mounted() {
    if (!EsriLoader.isLoaded()) {
      // preload the ArcGIS API
      await EsriLoader.loadScript({url: "https://js.arcgis.com/4.10/"}).then(() => {
        this.loadArcgisMods().then(arcgisApiMods => {
          this.arcgisApiMods = arcgisApiMods;
          this.$store.dispatch("config");
          this.appConfig = this.$store.state.config;
          this.init();
        });
      });
    } else {
      await this.loadArcgisMods().then(arcgisApiMods => {
        this.arcgisApiMods = arcgisApiMods;
        this.$store.dispatch("config");
        this.appConfig = this.$store.state.config;
        this.init();
      });
    }
  },
  methods: {
    loadArcgisMods() {
      return EsriLoader.loadModules([
        "esri/identity/OAuthInfo",
        "esri/identity/IdentityManager",
        "esri/views/MapView",
        "esri/WebMap",
        "esri/widgets/Search",
        "esri/core/watchUtils",
        "dojo/domReady!"
      ]).then(
        ([OAuthInfo, EsriId, MapView, WebMap, Search, watchUtils, dom]) => {
          return {
            OAuthInfo,
            EsriId,
            MapView,
            WebMap,
            Search,
            watchUtils
          };
        }
      );
    },
```

Are we missing something from our VueJS project that would allow us to pre-load the ArcGIS JavaScript API higher than version 4.8?

**Comment by jwasilgeo** [comment]
At first glance this seems to be an issue with something in your own app code and the JSAPI versions you have mentioned, rather than `esri-loader` or VueJS.  Occasionally there are breaking changes with method signatures and properties among JSAPI releases, so that's why I am curious about ruling this out first.

Have you already stepped back through the error message stack trace to see what, more specifically, is happening here in your code?  Also, if you haven't already, it would be helpful to look through the 4.8, 4.9, and 4.10 release notes (available at the bottom of this link) to see what JSAPI methods or properties may have changed on you.  <https://developers.arcgis.com/javascript/latest/guide/release-notes/index.html>

**Comment by jwasilgeo** [comment]
PS: For example, if you comment out any calls to your `this.init()`, do you still have errors?

**Comment by tomwayson** [comment]
Try getting rid of `dojo/domReady!` that's not needed when working w/ esri-loader.

**Comment by tomwayson** [comment]
Another thing that I would suggest is that you could greatly simplify your code by removing calls to `isLoaded()` and `loadScript()` and just use `loadModules()` - it will handle all that for you. It looks like all you need to do is pass `{url: "https://js.arcgis.com/4.8/"}`  as the second arg to `loadModules()` and get rid of `if (!EsriLoader.isLoaded()) {`. I would create a branch from the working 4.8 code, and make those changes, and once you have that working, _then_ try updating to 4.9, then 4.10.

**Comment by tommckennon** [comment]
Thank you for your prompt responses. To test these suggestions, I am now testing with just a down to the bare-bones Esri Map VueJs component, but unfortunately I am still stuck at 4.8 as the latest working version, while loading versions 4.9 and 4.10 still throws this same error mentioned above. Could it be that versions 4.9 and 4.10 of the JS API are not yet compatible with such VueJs components yet, making it a JS API issue, rather than an Esri Loader issue? Here is my bare-bones Esri Map VueJs component which still works at version 4.8, but no later.

`
<style>
@import url("https://js.arcgis.com/4.10/esri/css/main.css");
#esriMap {
  position: absolute;
  width: 100%;
  height: 650px;
}
</style>

<template>
  <div>
    <div id="esriMap"></div>
  </div>
</template>

<script>
import * as EsriLoader from "esri-loader";

export default {
  async mounted() {
    const options = {
      url: "https://js.arcgis.com/4.10/"
    };
    EsriLoader.loadModules(["esri/views/MapView", "esri/Map"], options)
      .then(([MapView, Map]) => {
        let map = new Map({
          basemap: "gray"
        });
        let mapView = new MapView({
          container: "esriMap",
          map: map
        });
      })
      .catch(err => {
        console.error(err);
      });
  }
};
</script>
`

**Comment by jwasilgeo** [comment]
Glad to see this bare-bones example, thanks for that; however, I have been using JSAPI 4.8, 4.9, and 4.10 successfully in VueJS 2.x components with the help of `esri-loader`.  I doubt this matters, but I've done something slightly different in my `<template>` and `MapView` constructor:

```html
<template>
  <div ref="component"></div>
</template>
```

```javascript
let mapView = new MapView({
  container: this.$refs.component,
  map: map
});
```

Is there an online code sharing platform we can all use together that supports VueJS components, and if so, can you put your bare-bones example there?

**Comment by tomwayson** [comment]
@tommckennon by chance is this error only happening in production builds of your app like in #148

**Comment by tommckennon** [comment]
@tomwayson . Sorry for not replying much sooner. My issue discussed here was resolved awhile ago. It turned out to be  a simple JS syntax error where I was incorrectly declaring a variable within the component code I was calling the Esri Loader methods from. Thank you still for your helpful feedback here.

**Comment by tommckennon** [comment]
> @tommckennon by chance is this error only happening in production builds of your app like in #148?

No, my issue was unrelated to the type of server environment I was running the application in. It turned out to be just a JS syntax error that broke the loadModules method when loading the ArcGIS JS API  beyond 4.8.
