### ISSUE TITLE
Add pkg.unpkg

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#146]
### Expected behavior

I expect to be able to load esri-loader from UNPKG like so:

```html
<script src="https://unpkg.com/esri-loader"></script>
```

### Actual behavior

<img width="702" alt="image" src="https://user-images.githubusercontent.com/662944/50317873-ce927b80-0472-11e9-9753-abcf63cc9909.png">

I think this is related to https://github.com/Esri/arcgis-rest-js/issues/420

**Comment by andygup** [comment]
Closing since this package is scheduled for deprecation at 4.29.
