### ISSUE TITLE
how can i extend from jsapi modules, if i load it using esri-loader

### ISSUE THREAD

**Issue by Aiooioo** [Esri/esri-loader#149]
Hi,
i am using your esri-loader in one of my web gis app, which developed with react. everything is going well, but now i am confused with some syntax. As all the modules in arcgis jsapi are loaded async, how could i just extend a new layer type from the base class in jsapi. 

In another app, i use "externals" in webpack config to exclude the jsapi modules, and i cound write a custom layer just like this:

import BaseTileLayer from 'esri/layers/BaseTileLayer';

class MyCustomLayer extends BaseTileLayer {
 ...
}

that would be confortable to me, but now, i have to load the  'esri/layers/BaseTileLayer' module asynchronously. 

So, anyone who has ever think about this scenario?

**Comment by tomwayson** [comment]
@Aiooioo 

See: https://github.com/Esri/esri-loader/issues/127#issuecomment-414903676

You should be able to make that class declaration _inside_ the callback you pass to `loadModules()`.

**Comment by Aiooioo** [comment]
wow, i got it. the es6 async import() func is a really wonderful solution .thanks

**Comment by tomwayson** [comment]
I assume you figured out how to do this. Feel free to reopen if needed.
