### ISSUE TITLE
404 errors for several modules on import - Vue

### ISSUE THREAD

**Issue by dmcdonald8** [Esri/esri-loader#151]
### Expected behavior

When trying to import the following modules using esri-loader's `load_modules()` in a Vue component I expected they should import correctly:

```
'esri/Map',
"esri/views/MapView",
"esri/graphic",
"esri/geometry/Geometry",
"esri/geometry/Extent",
"esri/SpatialReference",
"esri/tasks/GeometryService",
"esri/tasks/AreasAndLengthsParameters",
"esri/toolbars/draw",
"esri/symbols/SimpleFillSymbol"
```

### Actual behavior

Receiving 404 scriptError from dojoLoader for several, but not all, modules. Example: 
```
dojo.js: 24 GET https://js.arcgis.com/4.10/esri/SpatialReference.js net::ERR_ABORTED 404

dojo.js:24 Error: scriptError
    at k (dojo.js:5)
    at HTMLScriptElement.<anonymous> (dojo.js:23)
src: dojoLoader
dojo.js:24 info: (2) ["https://js.arcgis.com/4.10/esri/SpatialReference.js", Event]
dojo.js:25 .
```

When following the url from that error I get:

![esriloadererror](https://user-images.githubusercontent.com/35770168/53184455-f29a4680-35f4-11e9-9a0f-22890863d6db.PNG)

This happens with the following modules:
```
"esri/graphic"
"esri/tasks/AreasAndLengthsParameters"
"esri/SpatialReference"
"esri/toolbars/draw"
```

I've checked the docs for these modules and it looks to me that my import params are correct.

I've tried previous versions of the API back to 4.0, same thing

Perhaps I should be pre-loading? I'm trying to recreate something similar to this [sample](https://developers.arcgis.com/javascript/3/jssamples/util_measurepoly.html) as a Vue component. It is for an older version (3.27) of the API but I was hoping the versioning would be handled by the loader and the URLs seem to reflect that it's trying to do that.

Am I missing a step here or are these modules not meant to be imported in this way?

### Steps to reproduce the behavior
I will look into a JSFiddle or something similar, in the meantime here is a barebones example of my code that is not working
```
<template>
    <div id="map-panel"></div>
</template>

<script>
import * as EsriLoader from 'esri-loader'

export default {
  name: "Example",
  mounted() {
    EsriLoader.loadModules(['esri/Map',
                            "esri/views/MapView",
                            "esri/graphic",
                            "esri/geometry/Geometry",
                            "esri/geometry/Extent",
                            "esri/SpatialReference",
                            "esri/tasks/GeometryService",
                            "esri/tasks/AreasAndLengthsParameters",
                            "esri/toolbars/draw",
                            "esri/symbols/SimpleFillSymbol"])
      .then(([Map,
              MapView,
              Graphic,
              Geometry,
              Extent,
              SpatialReference,
              GeometryService,
              AreasAndLengthsParameters,
              Draw,
              SimpleFillSymbol]) => {
        const map = new Map({
          basemap: "oceans",
        })
        const mapView = new MapView({
          map: map,
          container: 'map-panel',
          zoom: 4,
          center: [10, 50],
        })
      })
      .catch(err => {
        console.log(err)
      })
    },
}
</script>

<style>
#map-panel {
  padding: 0;
  margin: 0;
  height: 800px;
  width: 800px;
}
</style>
```

**Comment by jwasilgeo** [comment]
It seems that you may be mixing in and trying to use JSAPI 3.x modules (the four that are failing to load), but using JSAPI 4.x.  Do I follow that correctly?  If so, you'll need to fully use either 3.x or 4.x but not both.  If you comment out attempting to bring in those four particular modules, it should work, is that right?

e.g. `"esri/SpatialReference"` at 3.x is now `"esri/geometry/SpatialReference"` in 4.x

**Comment by dmcdonald8** [comment]
@jwasilgeo 
Thank you! Yes I had thought it must be something like that.  

I was using some incorrect params, the problem was I was looking at an old version of the API Reference. that related to the guide I was reading. I've updated them to:

```
"esri/Graphic"
"esri/tasks/support/AreasAndLengthsParameters"
"esri/SpatialReference"
```

And they load correctly. Only one i'm not sure about is `"esri/toolbars/draw"` as I'm not sure what the 4.x equivalent is but I guess I'll need to do some research as a lot seems to have changed.

**Comment by jwasilgeo** [comment]
Good, I'm glad you've got a clear research path ahead of you!  Indeed a lot has changed at 4.x.  Drawing is a bit different, too, but I recommend looking around here for some widgets and lower-level modules that provide different levels of convenience and manual control for developers:

- https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Sketch.html
- https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Sketch-SketchViewModel.html
- https://developers.arcgis.com/javascript/latest/api-reference/esri-views-2d-draw-Draw.html
