### ISSUE TITLE
How to get type safety using esri-loader?

### ISSUE THREAD

**Issue by ca0v** [Esri/esri-loader#152]
I've had success loading the JS API dependencies using requirejs for a simple map but it's very slow (3-6 seconds) as it's needing to load nearly 1000 scripts.  I cannot figure out how to use the main dojo.js build script since all the "define"s are in the context of dojo and I'm wanting to use requirejs.

I found "esri-loader" thinking it might be loading the API more efficiently, but the point of access, loadModules, doesn't provide type safety.  My goal is to defer loading the map until it's actually needed and I don't want to load the esri version of dojo.js because it doesn't help me load modules via requirejs.  

If I do a custom build I'll be back to having my personal version of dojo.js, but still in the same situation.

But if "esri-loader" handled all that and provided a type-safe interface, I think I will be operational and performant.   

I guess I need to somehow move the dojo package registry into requirejs, but that seems like a really bad idea.

Can we get type-safety on loadModules?

**Comment by tomwayson** [comment]
> I don't want to load the esri version of dojo.js

That's what esri-loader does. The premise of esri-loader is that esri's dojo is going to be the most reliable and efficient way to load JSAPI modules.

I've never really thought about using esri-loader in a require.js app.

I am not exactly sure what you mean by "type-safety".

**Comment by tomwayson** [comment]
> Can we get type-safety on loadModules?

would something like this work for you? https://github.com/Esri/esri-loader/issues/119#issuecomment-477271822

**Comment by tomwayson** [comment]
@ca0v I've recently updated the [README section on using types](https://github.com/Esri/esri-loader#arcgis-types). Does that answer your question about type-safety?

**Comment by ca0v** [comment]
Any chance these redundancies can be eliminated?

```
    type MyModules = [
      typeof import("esri/map"),
      typeof import("esri/geometry/Extent")
    ];
    const [Map, Extent] = await (loadModules(
      ["esri/map", "esri/geometry/Extent"],
      options
    ) as Promise<MyModules>);
```

**Comment by tomwayson** [comment]
I'm not aware of a way generate types dynamically at run time, but if there is a way I'm open to looking into it.
