### ISSUE TITLE
How well does esri-loader work with React Native? 

### ISSUE THREAD

**Issue by nommuna2** [Esri/esri-loader#155]
Just wondering how well this will work if I tried to implement it into my React Native app?

**Comment by tomwayson** [comment]
I'd also be interested in hearing if/how people have used this in React Native.

I've never developed w/ React Native, so I may be wrong, but I'm under the impression that the only way to use the ArcGIS API for JavaScript is via a [WebView](https://facebook.github.io/react-native/docs/webview#docsNav) like:
 
https://snack.expo.io/BykzZgc2X
 
Obviously that simple example doesn’t show how the surrounding app would interact w/ the map, but I did a little further digging and found this JSAPI (Story Maps) in WebView example from UC 2016 to my attention:
 
http://proceedings.esri.com/library/userconf/devsummit16/papers/dev_int_45.pdf
https://github.com/skitterm/react-native-demo

I'm fairly certain the techniques in that example could be made into a reusable React Native component like this Leaflet example that exposes load and click events to the app and allows the app to add markers to the map, all via a WebView:
 
https://github.com/reggie3/react-native-webview-leaflet

I'm not entirely sure if/how esri-loader would fit into that solution though.

**Comment by nommuna2** [comment]
Yea, I was thinking of possibly making a custom component like the leaflet example you linked. Although, I am not sure how well React will play with the module loading patterns of the JS API. In any case I might give it a try and see how far I get.  Thanks for the examples!

**Comment by tomwayson** [comment]
> I am not sure how well React will play with the module loading patterns of the JS API

This should not be an issue b/c the web view will load a page that should only have the ArcGIS API on it (and no react), and that's why I suspect that esri-loader won't be needed.
