### ISSUE TITLE
Default to ArcGIS API 4.11

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#156]
### Expected behavior

esri-loader should default to loading v4.11 of the ArcGIS API, when it goes live (approx 3/28)

**Comment by tomwayson** [comment]
see https://github.com/Esri/esri-loader/pull/143/files for an example

**Comment by jburka** [comment]
Anything other than the JSAPI version numbers need to change? I've got a local fork running with 4.11/3.28 and all tests passing; I'd be happy to supply a PR...

**Comment by tomwayson** [comment]
Thanks @jburka but it looks like @ziveo beat you to it!

I'll have a release out later today.

**Comment by jburka** [comment]
Cool. Thanks!

**Comment by tomwayson** [comment]
Released as [2.9.0](https://github.com/Esri/esri-loader/releases/tag/v2.9.0)
