### ISSUE TITLE
Shorthand for loading 3x does not work (loader options version=3x)

### ISSUE THREAD

**Issue by davewilton** [Esri/esri-loader#165]
### Expected behavior

The readme shows the use of a shorthand to load 3x without the url:

![image](https://user-images.githubusercontent.com/2278405/55137994-8330ed00-5186-11e9-89c2-c7258a9a0d04.png)

This should load the 3x library

### Actual behavior

- It tries to load map from the 4x library
- Either the documentation needs updating or this bug fixing? Also version is not a valid property on the ILoadScriptOptions

![image](https://user-images.githubusercontent.com/2278405/55138038-99d74400-5186-11e9-950a-5c973cd76fd6.png)

### Steps to reproduce the behavior
Sandbox:
https://codesandbox.io/s/8y8vjvmy00?fontsize=14&module=%2Fsrc%2Fmapping.ts

**Comment by tomwayson** [comment]
That sandbox is using esri-loader@2.6, I _just_ added `version` in v2.8. If you update to 2.8, it works.

**Comment by davewilton** [comment]
Ah ok, that must have been hot off the press because I only made the sandbox a couple of days ago! tested and it works, cheers.
