### ISSUE TITLE
ILoadScriptOptions not exported in v2.8.0 TypeScript definition file

### ISSUE THREAD

**Issue by anwalkers** [Esri/esri-loader#166]
### Expected behavior

Would expect to be able to import ILoadScriptOptions from esri-loader

```import { ILoadScriptOptions } from 'esri-loader';```

### Actual behavior

![image](https://user-images.githubusercontent.com/3085122/55196483-bb2b3680-516c-11e9-984d-1799105a7e44.png)

### Steps to reproduce the behavior

https://stackblitz.com/edit/esri-loader-bug

**Comment by tomwayson** [comment]
Thanks @anwalkers - this should be fixed in [v2.9.1](https://github.com/Esri/esri-loader/releases/tag/v2.9.1)
