### ISSUE TITLE
How to zoom to layer's extent

### ISSUE THREAD

**Issue by bhargavi-voda** [Esri/esri-loader#173]
### Expected behavior

- I want the map to zoom to the extent of the feature layer on loading it for the first time and when clicking on the Home widget (similar to how arcgis online maps display the layers)
- Zoom to layer extent on load
- React 16.8, Npm 6.9, ArcGIS JS API 4.11

### Actual behavior

- If I don't provide the extent and spatial reference it displays the center point of the world.
- The map should take the layer's extent by default and only display that, but it shows the entire world map.
- No error messages in the console

### Steps to reproduce the behavior
[test.txt](https://github.com/Esri/esri-loader/files/3154587/test.txt)

**Comment by tomwayson** [comment]
The appropriate place for this sort of question is [GeoNet](https://community.esri.com/)

Once you figure out how to do this outside of your React app, like in a codepen based on one of the samples below, and you _still_ have trouble moving the working code into your React app via esri-loader, _then_ you can re-open this issue.
