### ISSUE TITLE
add preload tag to css files

### ISSUE THREAD

**Issue by pwang-esri** [Esri/esri-loader#181]
### Expected behavior
load main.css using preload
`<link rel="preload" href="style.css" as="style">` instead of `<link rel="stylesheet" href="style.css">`

this will also get rid of the lighthouse waring:

![a8197e00-9c15-11e9-9380-5b82f2df6afc](https://user-images.githubusercontent.com/3408470/63297399-24c7f080-c286-11e9-8fde-f9f0bec59667.png)

**Comment by andygup** [comment]
Good suggestion, if there's a way to make it the default with an option to use old style script loading might be better. `preload` is not supported in IE11 or in Firefox by default and both are currently supported browsers for the 4.x JS API.

**Comment by pwang-esri** [comment]
@tomwayson 
Now we are loading css before we load the map. But it would be nice if we can call `loadCss` once the page is rendered to preload css.

**Comment by oevans** [comment]
Any update on this one?

**Comment by tomwayson** [comment]
I'm not actively working on this. I'm not even totally sure what the ask is. Could you provide more detail about exactly what this means?

> Now we are loading css before we load the map.

Ideally show the code.

And then propose the new esri-loader API you'd like to see that would achieve the same (or equivalent) output.

**Comment by andygup** [comment]
Closing since this package is scheduled for deprecation at 4.29.
