### ISSUE TITLE
default to the light theme stylesheet when css is true

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#184]
### Expected behavior

Since 4.12 the ArcGIS API suggests the light theme (https://js.arcgis.com/4.12/esri/themes/light/main.css) as [the default stylesheet](https://developers.arcgis.com/javascript/latest/guide/get-api/).

We should do the same when the `css: true` option is passed.

### Actual behavior

We currently default to `esri/css/main.css`:

https://github.com/Esri/esri-loader/blob/b1ac4cc18f25d620c60d0c0b3cc09840ce4e3f45/src/utils/url.ts#L35-L38

**Comment by tomwayson** [comment]
The light theme css seems to be available all the way back to 4.1 https://js.arcgis.com/4.1/esri/themes/light/main.css

The question is, should we use that as the default for all 4.x versions, or just 4.12+?

cc @bsvensson

**Comment by stdavis** [comment]
I would vote to do it just for 4.12+. It might be jarring to upgrade `esri-loader` and get a different theme than you had before without changing any of your code.

Just my two cents. Thanks for the great project.

**Comment by bsvensson** [comment]
The "light" theme and the "main" theme are actually the same theme, same content. So there would be no differences :)
