### ISSUE TITLE
How can I draw a simple marker or a polyline and a sketch on mapimagelayer? please help

### ISSUE THREAD

**Issue by duynguyentdmu** [Esri/esri-loader#190]
//this is my code
import { Component, OnInit, ViewChild, ElementRef, Input, Output, EventEmitter } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from './../../../environments/environment';
import { Router } from '@angular/router';
import { loadModules, loadScript, utils } from 'esri-loader';
import { AuthServiceService } from '../../services/auth-service.service';

@Component({
  selector: 'app-p1009-bandocosohatang-gis',
  templateUrl: './p1009-bandocosohatang-gis.component.html',
  styleUrls: ['./p1009-bandocosohatang-gis.component.scss']
})
export class P1009BandocosohatangGisComponent implements OnInit {
  ipAddress: any;
  publicIP: any;
  @ViewChild('mapViewNode', { static: true }) private mapViewEl: ElementRef;
  map: any;
  layer1: any;
  view: any;
  sketch: any;
  pointGraphic: any;
  Graphic: any;
  editor: any;

  danhSachMarker: any;
  urlmap: any = 'http://localhost:6080/arcgis/rest/services//BanDoThuanAn/BanDoThuanAn/MapServer?f=jsapi';
  constructor(private http: HttpClient, private auth: AuthServiceService, private router: Router) { }

  ngOnInit() {
    this.loadBanDo();
  }

  loadBanDo() {
    loadModules([
      'esri/views/MapView',
      'esri/WebMap',
      'esri/Map',
      'esri/layers/MapImageLayer',
      'esri/symbols/SimpleMarkerSymbol',
      'esri/Map',
      'esri/widgets/Editor',
      'esri/widgets/Sketch',
      'esri/layers/GraphicsLayer',

      'esri/views/MapView',
      'esri/layers/MapImageLayer',
      'esri/request',
      'esri/Graphic',
      'dojo/_base/array',
    ]).then(([MapView, WebMap, Map, MapImageLayer, Editor, Graphic, GraphicsLayer, Sketch]) => {
      this.Graphic = Graphic;
      const layer = new GraphicsLayer();

      this.layer1 = new MapImageLayer({
        url: 'http://localhost:6080/arcgis/rest/services/BanDoThuanAn/BanDoThuanAn/MapServer/'
      });

      this.map = new Map({
         basemap: 'dark-gray',
        layers: [this.layer1]
      });
      // and we show that map in a container w/ id #viewDiv
      this.view = new MapView({
        map: this.map,
        container: 'viewDiv',
        zoom: 17,
        center: [106.698021, 10.901081] // [-99, 39]
      });

      this.editor = new Editor({
        view: this.view
      });

      this.sketch = new Sketch({
        layer: layer,
        view: this.view
      });

      this.view.ui.add(this.sketch, 'top-right');

      // ===================

      this.view.on('click', (evt) => {
        // this.layToaDo(this.view.toMap({ x: evt.x, y: evt.y }));
        const coords1 = this.view.toMap({ x: evt.x, y: evt.y });
        const a1 = coords1.latitude.toFixed(6); // vi do
        const b1 = coords1.longitude.toFixed(6); // kinh do
        console.log(a1, b1);
      });

    })
      .catch(err => {
        // handle any errors
        console.error(err);
      });
  }

  layToaDo(pt) {
    const coords = 'Vĩ độ: ' + pt.latitude.toFixed(6) + '; Kinh độ: ' + pt.longitude.toFixed(6) +
      ' | Scale 1:' + Math.round(this.view.scale * 1) / 1 +
      ' | Zoom ' + this.view.zoom;
    console.log(coords);
  }

  themDanhSachDiem(pt) {
    this.danhSachMarker = [];
    this.danhSachMarker.push('[' + pt.longitude.toFixed(6) + ',' + pt.latitude.toFixed(6) + ']');
  }
}

**Comment by andygup** [comment]
@duynguyentdmu Hi, my recommendation is to first try and get this functionality working outside of Angular in a stand-alone JavaScript app. Or create a working example in StackBlitz: https://stackblitz.com/edit/angular-cli-esri-map2?file=src/main.ts. 

If you build a stand-alone JS app and find your issue is not related to `esri-loader` please post those questions on GeoNET here: https://community.esri.com/community/developers/web-developers/arcgis-api-for-javascript
