### ISSUE TITLE
about dijit/Measurement

### ISSUE THREAD

**Issue by waiwaiTaDady** [Esri/esri-loader#195]
when i use this dijit ,i lost the CSS,how to resolve this problem?thanks

 componentWillMount(){
        loadCss('http://localhost/arcgis_js_api/library/3.29/esri/themes/calcite/dijit/calcite.css');
        loadCss('http://localhost/arcgis_js_api/library/3.29/esri/themes/calcite/esri/esri.css');//themes/calcite/esri/esri.css
        // desbugger
        // loadCss('3.29')
    }

    lengthMeasure=()=>{
        var _this = this;
        var map = _this.props.mapControl;      
        esriLoader.loadModules([
            "dojo/dom",
            "esri/Color",
            "dojo/keys",
            "dojo/parser",

            "esri/config",
            "esri/sniff",
            "esri/map",
            "esri/SnappingManager",
            "esri/dijit/Measurement",
            "esri/layers/FeatureLayer",
            "esri/renderers/SimpleRenderer",
            "esri/tasks/GeometryService",
            "esri/symbols/SimpleLineSymbol",
            "esri/symbols/SimpleFillSymbol",

            "esri/dijit/Scalebar",
            "dijit/layout/BorderContainer",
            "dijit/layout/ContentPane",
            "dijit/TitlePane",
            "dijit/form/CheckBox",
            "dojo/domReady!"
        ],  {url : `${BASICCONFIG.GISAPI}/dojo/dojo.js`}).then(([
            dom, Color, keys, parser,
            esriConfig, has, Map, SnappingManager, Measurement, FeatureLayer, SimpleRenderer,
             GeometryService, SimpleLineSymbol, SimpleFillSymbol
        ])=>{
            map.graphics.clear();
            if (_this.mapClickEvent) {
                _this.mapClickEvent.remove();
                _this.mapClickEvent = null;
            }
            if (_this.props.mapControl.tb) {
                _this.props.mapControl.tb.deactivate();
                _this.props.mapControl.tb = null;
            }

            //This service is for development and testing purposes only. We recommend that you create your own geometry service for use within your applications
            esriConfig.defaults.geometryService = new GeometryService("http://localhost/arcgis/rest/services/Utilities/Geometry/GeometryServer");

            var measurement = new Measurement({
            map: map
            }, dom.byId("measurementDiv"));
            measurement.startup();
        });
    };

 render() {
        return (
            <div>
            <div className="mapTool" onClick={this.measureLength}>
                测距
            </div> 
                <div id="measurementDiv"></div>
            </div>                       
        )
    }

**Comment by tomwayson** [comment]
What CSS files do you see loaded in the network traffic?

**Comment by waiwaiTaDady** [comment]
> What CSS files do you see loaded in the network traffic?

![企业微信截图_15717923618763](https://user-images.githubusercontent.com/29618192/67347060-93217b80-f573-11e9-92cd-15caac335067.png)

arcgis api 3.29 dijit/measurement ， i don‘t know how to set the style ，the css file was looaded but invalid

**Comment by tomwayson** [comment]
Have you read https://developers.arcgis.com/javascript/3/jshelp/css.html

**Comment by tomwayson** [comment]
also, I'd start by just loading the CSS using static `<link>`s in your HTML document. Once that works, you can then start looking into using `loadCss()`.

**Comment by jwasilgeo** [comment]
@waiwaiTaDady were you able to get this resolved?

**Comment by waiwaiTaDady** [comment]
oh，thanks for attention about this.I did not find any good method to solve this problem,so....i take the most primitive method---using a Css  cover the Measurement Css of ArcgisAPI ('Copy' the style).em.....you have some good solution？
