### ISSUE TITLE
the dojoConfig option should be a string that sets the data-dojo-config

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#197]
### Expected behavior

users should pass `dojoConfig` as a string (instead of an object) and it should be added as the script's `data-dojo-config` attribute.

### Actual behavior

users pass `dojoConfig` as an object and it overwrites `window.dojoConfig`:

https://github.com/Esri/esri-loader/blob/58b17ca95344b302284c9af81dd0256ded4cb9cc/src/script.ts#L125-L129

The purpose would be to try and eliminate a global side effect and use the [dojoConfig API](https://dojotoolkit.org/documentation/tutorials/1.10/dojo_config/index.html) that is most appropriate to how this library works (inserts a script tag).

This will be a breaking change, but this library is due for a major version bump and some culling.

**Comment by beginor** [comment]
A lot of things can not be configured by the script tag.

**Comment by tomwayson** [comment]
Thank you for your feedback, @beginor. In those cases, couldn't you just set `window.dojoConfig` yourself instead?

**Comment by beginor** [comment]
Is the `dojoConfig` option going to be removed? or it will be changed as string in future version?

**Comment by tomwayson** [comment]
my idea was to change to string at the next breaking change (v.3.0.0).

Bear in mind that I have no time to work on this, nor any plans to do so for the foreseeable future. This is just my idea for what should happen.
