### ISSUE TITLE
lazy load CSS by default

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#198]
### Expected behavior

Calling `loadModules()` w/o any options will lazy load the ArcGIS API CSS

### Actual behavior

You have to set the `css: true` option b/c @andygup and his Angular Army have some special way of loading CSS in Angular applications.

Well, I'm tired of the @andygup's of this world forcing the rest of us to do extra work. I say we take back esri-loader and force them to use `css: false`! Where my React people at?

Obviously @andygup wasn't the only thing holding us back from this. This is a breaking change and would require a major version bump, but as I said in #197 we're due for that.

We'd have to decide what to do about when `url` is passed w/o `css`. I think the simplest thing is that we don't load any CSS in that case. So `css: true` is ignored if `url` is passed. We might even be able to implement that part now as a patch since it's effectively a bug to load CSS from the CDN when you're using a local build of the API.

**Comment by andygup** [comment]
LOL. Going forward it makes sense to let css lazy load by default (+ major version bump). The current approach made sense back in the stone age (pre-circa 2016) when Angular apps outnumbered React/Vue/etc, etc apps at approximately 3,138,435,235.4 : 1. I think we can all agree that ratio is maybe a tiny smidge less today. 😄

**Comment by tomwayson** [comment]
Meh, I'm over this. I don't want to have to explain the different behavior when you use `url` instead of `version`.
