### ISSUE TITLE
__esri.RequestInterceptor.error() missing error parameter

### ISSUE THREAD

**Issue by als9xd** [Esri/esri-loader#217]
### Expected behavior

Not sure if this is the best place for this ticket...

- The type definition of __esri.RequestInterceptor.error() should have an error argument.
- Environment @types/arcgis-js-api@4.14.0, esri-load@2.13.0

### Actual behavior

- the type definintion for __esri.RequestInterceptor.error() is missing error parameter

### Steps to reproduce the behavior

1. remove ```// @ts-ignore``` s from following link
2. https://stackblitz.com/edit/react-ts-w9x3nc?file=index.tsx

**Comment by tomwayson** [comment]
Thanks @als9xd 

The appropriate place for type errors is:

https://github.com/Esri/jsapi-resources/issues

It looks like this may already have been reported: https://github.com/Esri/jsapi-resources/issues/201

I'm going to close this. If you are still experiencing issues please follow up on the above issue.
