### ISSUE TITLE
Could not load other components? Is it dojo.js 

### ISSUE THREAD

**Issue by dzungld** [Esri/esri-loader#221]
### Expected behavior
I followed all the guide from esri-loader document to set it up and use it in my Angular Project. At first, it worked with simple loading. However, when I tried to load more component (eg: WMSLayer, GeoJSONLayer... - because there are many kind of layers in my map) It fail to load:

- Describe what you expected or wanted to happen.
Could load and use more ESRI API Components eg: WMSLayer, GeoJSONLayer... 
- What you are trying to achieve?
I tried many times to load many kind of modules of ArcGIS API including over the Internet and locally
- Describe your environment/framework and be specific with version numbers (e.g. React 16.2, react-router 4.2, redux 3.7, node 8.3).
OS: Windows 10 Pro 64
Angular: 8.3.23
npm: 6.14
node: 12.14.1
ArcGIS API: 4.14

### Actual behavior
- Describe what occurs in your code.
These code worked
`const [Map, MapView] = await loadModules([
        "esri/Map",
        "esri/views/MapView"]);`
AND
`const [Map, MapView, Point] = await loadModules([
        "esri/Map",
        "esri/views/MapView",
        "esri/geometry/Point"]);`

But these ones didn't:
`
const [Map, MapView, GeoJSONLayer] = await loadModules([
        "esri/Map",
        "esri/views/MapView",
        "esri/layers/GeoJSONLayer"]);
`
OR
`
const [Map, MapView, WMSLayer] = await loadModules([
        "esri/Map",
        "esri/views/MapView",
        "esri/layers/WMSLayer"]);
`
- Specifically, what seems to work differently than you intended?
- Provide any error messages you see in the console.
Anytime when I tried to load more than Map and MapView component, this error happens and map could be not displayed:

```
EsriLoader:  Error: findModules
    at contextRequire (bootstrap:356)
    at req (bootstrap:234)
    at eval (esri-loader.js:236)
    at new ZoneAwarePromise (zone.js:930)
    at requireModules (esri-loader.js:233)
    at loadModules (esri-loader.js:267)
    at GisSimpleMapService.eval (gissimplemap.service.ts:32)
    at step (tslib.js:135)
    at Object.eval [as next] (tslib.js:116)
    at eval (tslib.js:109)
```
The error in: dojo.js:688

**Comment by andygup** [comment]
@dzungld did you use this repo => https://github.com/Esri/angular-cli-esri-map#angular-cli-esri-map? 

That sounds more like a project configuration issue than an angular issue.

**Comment by tomwayson** [comment]
Nothing jumps out at me w/ the code you show. 

I would try [setting up a codepen](https://github.com/Esri/esri-loader#using-a-module-script-tag) and then try calling your code like: 
 `const [Map, MapView, GeoJSONLayer] = await loadModules([ "esri/Map", "esri/views/MapView", "esri/layers/GeoJSONLayer"]);` and see if that works.

**Comment by andygup** [comment]
I also tested it locally using a fresh install of `angular-cli-esri-map` and didn't have any issues.

**Comment by dzungld** [comment]
Thanks, I think my problem could be trying to install both webpack and esri-loader and forgot to remove many configurations that I found in the Internet. I will try to start with a fresh one again. Thanks

**Comment by andygup** [comment]
Sounds good. I'll go ahead and close this issue for now. If the problem reappears feel free to let us know.
