### ISSUE TITLE
Ionic 5 framework with esri-loader

### ISSUE THREAD

**Issue by louza287** [Esri/esri-loader#222]
I want to use esri-loader library at ionic project to make mobile application
I installed esri-loader by running "npm install --save esri-loader"

this is my code

import { loadCss,loadScript,loadModules,setDefaultOptions } from 'esri-loader';
export class HomePage implements OnInit{
@ViewChild('map', {static: true}) mapElem: ElementRef;
async getGeo()
{
  await this._platform.ready();
  try {
  loadCss("https://js.arcgis.com/4.14/esri/css/main.css");
  setDefaultOptions({version:'4.14'});
    const [
            Map
            , MapView,Extent,FeatureLayer,Graphic,Search,Locator
          ]: any
      = await loadModules([
        'esri/Map',
        'esri/views/MapView',
        'esri/geometry/Extent',"esri/layers/FeatureLayer"
        ,"esri/Graphic","esri/widgets/Search","esri/tasks/Locator"
      ]).catch(err=>{
        alert("catchError "+err);
      });

    let map = new Map({
      basemap: 'streets'
    });
    // Inflate and display the map
    let view = new MapView({
      container: this.mapElem.nativeElement,
      center: [-78.6382, 35.7796],
     zoom: 12,
      map: map
    });

} catch (error) {
  alert( error);
}
}
}
ngOnInit() {
   this.getGeo();
  }
The map is working in browser but not in device.
I got errors when I built an apk and installed it on android device 
I got 2 error messages
the first one is **"there was an error attempting to load https://js/arcgis.com/4.14/"**
the second one is **"EsriLoader:TypeError: Cannot read property '0' of undefined"**

**Comment by andygup** [comment]
@louza287 Is the first error message an exact copy/paste? The URL is wrong some reason `https://js/arcgis.com`? It should be `https://js.arcgis.com...`. That looks like an Android pathname issue

**Comment by louza287** [comment]
@andygup sorry I wrote the url here wrong but it is written right in the code

**Comment by andygup** [comment]
Have you tried just using the `esri-loader` default settings? For example:

```javascript
\\ loadCss("https://js.arcgis.com/4.14/esri/css/main.css");
\\ setDefaultOptions({version:'4.14'});
setDefaultOptions({ css: true });

```

**Comment by louza287** [comment]
I have tried the default setting but the map did not show and I got the same error messages

**Comment by louza287** [comment]
thx @andygup 
the map is shown by removing android platform and adding it again

**Comment by andygup** [comment]
@louza287 it sounds like you figured it out? If so we'll go ahead and close the issue.

**Comment by andygup** [comment]
Closing.
