### ISSUE TITLE
Why esri-leaflet is faster than esri-loader

### ISSUE THREAD

**Issue by kynhbdg** [Esri/esri-loader#229]
How does esri-leaflet render map is faster than esri-loader.
And Can I config esri-loader like esri-leaflet?
I use angular 8 and esri-loader very slow when load map, i also use ChangeDetectionStrategy and runOutsideAngular but no effect.
Can I config esri-loader like esri-leaflet to get better performance?
You can see the comparision below
http://esri.github.io/esri-leaflet-renderers/spec/comparisons.html

**Comment by jwasilgeo** [comment]
That reminds me of an old comment (in 2015!) I made in the esri-leaflet-renderers repo.  If you are using the ArcGIS API for JavaScript [**_version 3_**](https://developers.arcgis.com/javascript/3/), the first few comments in that discussion may be interesting to you.

https://github.com/Esri/esri-leaflet-renderers/issues/90

But that was focused on the _perceived visual_ timings of how long user pan and zoom actions occur in that version of ArcGIS API for JavaScript.

**Comment by jwasilgeo** [comment]
Can you elaborate on what you mean by better performance?  What are you measuring and would like to see differently?

**Comment by tomwayson** [comment]
This question lacks detail, likely doesn't pertain to esri-loader itself unless the author is lazy-loading w/ esri-loader and not w/ esri-leaflet, and potentially subjective.

I'm closing it due to lack of activity.
