### ISSUE TITLE
Excessive change detection cycles in Angular 10 application with Esri JS API 4.15

### ISSUE THREAD

**Issue by vitale232** [Esri/esri-loader#234]
This issue is not actually an `esri-loader` issue. I'm hoping to start a discussion regarding the material presented here and gauge interest in a PR of the README to help disseminate what I believe is useful information. This issue is possibly related to #215.

### Expected behavior

I'm using `esri-loader` to bring the ArcGIS JS API into an Angular application. I would expect that once the API is loaded, it would have no effects on Angular change detection. I've been experimenting with this using Angular 8, 9, and 10.

### Actual behavior

Instantiating and rendering a map to the DOM is triggering excessive Angular change detection cycles.

### Steps to reproduce the behavior

You can use [this StackBlitz](https://stackblitz.com/edit/esri-ng-change-detection?file=src/app/app.component.ts) to reproduce the issue in Angular 10.

The `app.component.ts` implements the [`ngAfterViewChecked`](https://angular.io/api/core/AfterViewChecked) Angular lifecycle hook. It calls `console.log` every time there is a change detection cycle.

`app.component.ts` also has a boolean property called `runOutsideAngular`. That property is set to `true` by default. If you open the console, you'll see that there were a few Angular change detection cycles, but nothing overly excessive.

If you set `runOutsideAngular` to `false` and open the console, you'll see that the `ngAfterViewChecked`  lifecycle hook is invoked multiple times per second with no end in sight.

### Workaround

I'm learning as I go with this, but here is my understanding... Angular's change detection involves a library called [Zone.js](https://github.com/angular/angular/tree/master/packages/zone.js). "Zone is an execution context that persists across asynchronous tasks."

[Here is a good guide that explains Zone.js in Angular.](https://angular.io/guide/zone)

Async operations such as an event, `setTimeout` , a Promise resolving, etc. all have the potential to mutate data. If application data is mutated, change detection should be run to render the updates to the DOM. To this end, Angular uses Zone.js to instrument asynchronous operations so that it can observe their resolution and automatically trigger change detection. Key to this conversation, **all** async operations are run in the Angular Zone by default.

Since the Esri JS API is being instantiated inside of the Angular Zone, all async operations in the API will trigger change detection. This means that any async operations used internally by the Esri JS API and any of the [listed Web APIs](https://github.com/angular/angular/blob/master/packages/zone.js/MODULE.md) used internally by Esri JS API will trigger change detection in your Angular application, which is probably not what you want.

The Angular team has included a Service that is designed to address situations like this called [`ngZone`](https://angular.io/guide/zone#ngzone-1). If you pass a callback into the `runOutsideAngular` function, the callback will executed outside of the Angular Zone, thus it will not trigger Angular change detection.

I've found it quite useful to use `ngZone.runOutsideAngular` while working with the Esri JS API. I run my map initialization functions in that method, which is providing a low-cost performance boost. There have been a few occasions while interacting with the Esri JS API where I would expect change detection to trigger, but it did not. I've been able to address these issues by either invoking `ngZone.run` to ensure that the function runs in the Angular Zone, or in some situations I'll manually trigger change detection using the Angular [`ChangeDetectorRef`](https://angular.io/api/core/ChangeDetectorRef).

**Comment by andygup** [comment]
Thanks @vitale232! I've opened an issue at https://github.com/Esri/angular-cli-esri-map/issues/70 so let's continue the discussion over there since it is an Angular-specific issue. 

Those are all excellent points and definitely something that should be publicly documented in https://github.com/Esri/angular-cli-esri-map as it relates to `esri-loader` **or** `arcgis-webpack-plugin`.  Almost all of the discussions up to this point have been private/confidential, so it will be great to get these ideas out in the open in a way that everyone can consider them.



I'll go ahead and close this issue.
