### ISSUE TITLE
Error: multipleDefine without jQuery 

### ISSUE THREAD

**Issue by EricKit** [Esri/esri-loader#235]
I have read all the posts from the previous multipleDefine issues on esri-loader. I cannot figure out what is going on. Live demo: https://dieselplanning.com/ao works fine. Click the map icon on the bottom left of the side bar and maps will switch from Apple's MapkitJS to the Esri ones. 

https://dieselplanning.com/test starts with the Mapkit JS maps, then switches to Esri. multipleDefine errors, but not like the one's from the previous post.

Background:

I think mapkitjs and dojoLoader are conflicting, I'm just not sure how. MapkitJs loses its ability to rotate when esri-loader's `loadModules` is used. If I add `loadModules` to a project, and load nothing (but make the call), MapkitJS loses the ability to rotate.

First I load the mapkitjs script and initialize it. Then, via esri-loader I load the arcgis scripts after mapkit is initialized. Then I create the apple Map. Then, after the user clicks, I destroy that map and create the Esri map. This causes the error.

If I load the Esri map first, then create the Apple Mapkit map, it's fine (except the ability to rotate mapkit). I can switch back and forth between them. But if I create an apple map first, then an Esri map, it breaks. Of note, I don't get this error until I create the map. It does not happen when esri-loader finishes loading the modules. I can load the modules, wait a minute, then create the arcgis map (after the mapkit map) and it'll break there. I don't know where to start debugging this and searching the forums shows most things are jQuery related. I've made sure mapkit isn't loading jQuery onto my window, it's not. 

You can see the error real time on the links above, but here is a screen shot:

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/4143477/86876237-1ef31d80-c099-11ea-8414-0c8dbe9229fd.png">

I'll gladly answer any questions, if this has nothing to do with esri-loader and all to do with dojoLoader and incompatibilities I apologize.

I also can post any code / publicly share the whole repository if needed. The mapkit loader and esri-loader are each providers with useContext in React.

**Comment by tomwayson** [comment]
Instead of having the map icon click call `loadModules()`, I suggest you try temporarily removing esri-loader from your project and have the click handler directly inject a script tag that points to the ArcGIS API like:

https://github.com/Esri/esri-loader/blob/209db0c24577ac9aeaef1999a49fad2be9c0ac3a/src/script.ts#L11-L13

https://github.com/Esri/esri-loader/blob/209db0c24577ac9aeaef1999a49fad2be9c0ac3a/src/script.ts#L140

If you see the same error, then this is not related to esri-loader.

**Comment by EricKit** [comment]
The click handler doesn't load esri-loader. This happens when the page loads. However, I run into typescript issues when I load it this way. This is how I load mapkitjs. I'll give it another try and report back.

**Comment by EricKit** [comment]
Yes it does give the same error with the script being manually loaded, I'm not sure where to look to solve this one.

**Comment by EricKit** [comment]
Turns out loading the mapkit API first mattered.  But then when you actually create your first map, it makes more calls and must use the define. So the solution has been to load mapkit, then create a map, destroy the map, then load arcgis.
