### ISSUE TITLE
How about add esriConfig to ILoadScriptOptions

### ISSUE THREAD

**Issue by beginor** [Esri/esri-loader#237]
According to the [esri/config](https://developers.arcgis.com/javascript/latest/api-reference/esri-config.html) api in arcgjs js api sdk,  we can use the global `esriConfig` variable to initialize the `esri/config` module, how about add this variable to `ILoadScriptOptions` interface , just like `dojoConfig`?

<https://github.com/Esri/esri-loader/blob/master/src/script.ts#L52>

**Comment by tomwayson** [comment]
Thank you for the suggestion @beginor.

However, I don't think that is supported in [3.x](https://developers.arcgis.com/javascript/3/jsapi/esri.config-amd.html).

Also, I wonder is this any better than just setting `window.esriConfig` directly?

**Comment by beginor** [comment]
We can also define `window.dojoConfig` directly, and is that any better then in `ILoadScriptOptions` ？ 😂

**Comment by tomwayson** [comment]
I think using `window.dojoConfig` is better than using `ILoadScriptOptions.dojoConfig`.

That is why I opened #197. I think using `ILoadScriptOptions` is more problematic (causes side effects) than it is worth.

**Comment by arvinthvikas** [comment]
how to change map language using dojoconfig
