### ISSUE TITLE
Feature Request : Add dojo2 to the README

### ISSUE THREAD

**Issue by sebilasse** [Esri/esri-loader#242]
This is just working wonderful with [dojo2](https://dojo.io) returned as dom like
```TypeScript
return dom({
  node,
  onAttach: () => {
      loadModules(['esri/views/MapView', 'esri/WebMap'])
        .then(([MapView, WebMap]) => {
          // rest of the example
```

So maybe you want to add the [dragon](https://dojo.io/logo.2eZA5N70.svg) to the README …

**Comment by tomwayson** [comment]
Thanks @sebilasse 

There _is_ a [Dojo 2 section](https://github.com/Esri/esri-loader#dojo-2).

If I add any logos it'd probably be this one:

<a title="Rich Harris / MIT (http://opensource.org/licenses/mit-license.php)" href="https://commons.wikimedia.org/wiki/File:Svelte_Logo.svg"><img width="256" alt="Svelte Logo" src="https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Svelte_Logo.svg/256px-Svelte_Logo.svg.png"></a>
