### ISSUE TITLE
Cant generate mapview

### ISSUE THREAD

**Issue by bigalnz** [Esri/esri-loader#245]
I am copying the map-view component documented here : [https://developers.arcgis.com/javascript/latest/guide/angular/](url)

When I try this I get the following error:

  15:3  error    expected call-signature: 'ngOnInit' to have a typedef (tslint:typedef)                                                                                    @typescript-eslint/tslint/config
  19:9  error    expected call-signature: 'initializeMap' to have a typedef (tslint:typedef)                                                                               @typescript-eslint/tslint/config
  36:9  error    Expected property shorthand                                                                                                                               object-shorthand
  47:3  error    Lifecycle interface OnDestroy should be implemented for method ngOnDestroy. (https://angular.io/styleguide#style-09-01) (tslint:use-lifecycle-interface)  @typescript-eslint/tslint/config
  47:3  error    expected call-signature: 'ngOnDestroy' to have a typedef (tslint:typedef) 

This seems to mainly relate to :   

export class EsriMapComponent implements OnInit {
  @ViewChild("mapViewNode", { static: true }) private mapViewEl: ElementRef;
  view: any;
  constructor() { }

  ngOnInit() {
    this.initializeMap();
  }

  async initializeMap() {
    try {

MapViewEl is not being declared properly?

**Comment by andygup** [comment]
Hi @bigalnz, maybe try using this working example as a starting point: https://github.com/Esri/angular-cli-esri-map.

**Comment by bigalnz** [comment]
Hi Andy,
For the benefit of anyone else, I had rather strict settings in my tsconfig (strict: true) so to get around this I made mapViewEl optional:
`export class EsriMapComponent implements OnInit, OnDestroy {
  @ViewChild("mapViewNode", { static: true }) private mapViewEl!: ElementRef;`

Since the methods dont return anything I added void:

`  ngOnInit(): void {
    this.initializeMap();
  }

  async initializeMap(): Promise<void> {

`

**Comment by andygup** [comment]
Glad you got it figured out, I'll close the issue.
