### ISSUE TITLE
esri-loader in hybrid angular app with ngUpgrade

### ISSUE THREAD

**Issue by nickyates987** [Esri/esri-loader#253]
### Expected behavior

- To be able to use ArcGis 3.X in our Angular.js 1.4 and ArcGis 4.X in our Angular 10 upgraded pages.
- Load different versions of 
- ArcGis 3.18 , ArcGis 4.17 ).

### Actual behavior

- The legacy code is loading ArcGis 3.18, and our new code is using esri-loader but even when configured to use 4.17, it's loadinf version 3.18

In app.module.ts

import { setDefaultOptions } from 'esri-loader';
setDefaultOptions({ version: '4.17' })

In our Angular 10 map component using 4.x code

 loadModules([
            'esri/Map',  
            'esri/views/MapView'
        ])
            .then(([EsriMap, EsriMapView]) => {
                const map = new EsriMap({
                    basemap: 'streets'
                });

                const mapView = new EsriMapView({
                    container: this.mapViewEl.nativeElement,
                    center: [this.Long, this.Lat],  
                    zoom: 10,
                    map: map
                });

                console.log("esri map loads");
            })
            .catch(err => {
                console.error(err);
            });

### Steps to reproduce the behavior

Just run the app, happens every time on loading

Get this error in the console as if esri-loader is loading the old version of ArcGis.

3.18:35 GET https://js.arcgis.com/3.18/esri/views/MapView.js net::ERR_ABORTED 404
GET https://js.arcgis.com/3.18/esri/Map.js net::ERR_ABORTED 404

I just want to know if it's possible to do this in a Hybrd angular app.

**Comment by nickyates987** [comment]
I've been through the esri-loader code and it won't load the library again if it's already been loaded. As the 3.x ArcGis library is already loaded for angularJS it won't load the 4.x ArcGis library.

**Comment by andygup** [comment]
@nickyates987 just a heads-up, in our upcoming 4.18 release in December we are releasing a beta that uses ES modules. When using the ES modules build you can [`npm install @arcgis/core`](https://www.npmjs.com/package/@arcgis/core) and then use native imports. Here's an example: https://github.com/Esri/feedback-js-api-next/tree/master/esm-samples/jsapi-angular-cli. 

```javascript
import Map from '@arcgis/core/Map';
import MapView from '@arcgis/core/views/MapView';
```

**Comment by tomwayson** [comment]
This appears to be a duplicate of #223.

@andygup are you suggesting that @nickyates987 might be able to use `@arcgis/core` primarily, but then use `esri-loader` in the places where he needs 3.x? That's an interesting (and somewhat horrifying) idea.

**Comment by andygup** [comment]
@tomwayson no sir. I recommend running only 4.x in new applications. 

@nickyates987 I'm curious about the use cases that still require 3.x?
