### ISSUE TITLE
drop IE support?

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#259]
Now that JSAPI 4.18 no longer supports IE, should esri-loader?

Well, you can still use esri-loader w/ versions <4.18, including 3.x, and those versions support IE. So here's my plan.

For now we'll release esri-loader 3.0.0 that defaults to 4.18 but still works w/ 3.x (#254) and is still distributed as ESM/ES5 in order to offer the same [current level of browser support](https://github.com/Esri/esri-loader/blob/a6c1bd60b8599cc2d89a05457e4b84e5782d78b4/README.md#browsers)

Later, say, when the ESM build is out of beta later next year, we could change the esri-loader transpile target to E2017 and cut an esri-loader 4.0.0 release that no longer supports IE. We'd likely drop the UMD build at that time too?

Isn't that clever? esri-loader 4.x would default to the latest JSAPI 4.x, and esri-loader 3.x would be for JSAPI 3.x.

**Comment by jimmywarting** [comment]
Most tech companies (LinkedIn, Zendesk, Microsoft 365, etc) has already dropped support for IE11.

Microsoft themselves will drop support in August (https://www.theverge.com/2020/8/17/21372487/microsoft-internet-explorer-11-support-end-365-legacy-edge).

https://death-to-ie11.com/

**Comment by andygup** [comment]
Closing. IE is no longer supported.
