### ISSUE TITLE
ArcGIS JS API 4.18 Sketch Widget graphics and graphic selection often do not render in Angular 11 application

### ISSUE THREAD

**Issue by vitale232** [Esri/esri-loader#262]
### Expected behavior

I am trying to use the [Sketch Widget](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Sketch.html) to capture user-created gometries in an Angular 11 application with `esri-loader`.

|Dependency|Version|
|-|-|
|ArcGIS JS API|4.18|
|esri-loader|2.15.0 & 3.0.0|
|Angular|11.0.6|

### Actual behavior

The widget loads properly and it is successfully added to the `view.ui`. When creating a graphic, the widget renders the in-progress graphic correctly, with the new 4.18 styling. The `create`, `update`, and `delete` events all seem to fire correctly. This is all as expected.

However, when the sketch create is complete, the new graphic disappears from the view. It can still be selected, but the graphic is not visible to the user. Sometimes selecting the graphic will bring it back into view. This issue is most prevalent on the first graphic added to the map.

Here is a gif, similar to the gif in the sketch docs, that exemplifies my issue:
![sketch-issue](https://user-images.githubusercontent.com/8504254/104103273-2cb77480-526f-11eb-824a-28617ab505cd.gif)

### Steps to reproduce the behavior

The issue described here is replicated in this Stackblitz:
https://stackblitz.com/edit/ng-esri-418-sketch?file=src%2Fapp%2Fesri-map%2Fesri-map.component.ts

I'm able to replicate on my Windows 10 machine in up-to-date Chrome and Firefox.

FWIW, the widget works as expected in [sample from the docs](https://developers.arcgis.com/javascript/latest/sample-code/sketch-geometries/index.html) on my system.

**Comment by andygup** [comment]
@vitale232 thanks for reporting. This is a known issue in JS API 4.18. The temporary workaround is to revert to 4.17. We're tentatively aiming to have this fixed at 4.19 (April).

**Comment by vitale232** [comment]
Thanks, @andygup. Looking forward to 4.19. We love this widget! I'll let you close this as you see fit.

**Comment by andygup** [comment]
Closing as a known issue.

**Comment by nbabel** [comment]
I can confirm that this issue is also occurring with the '@arcgis/core' es modules at 4.18, not just the esri-loader.
