### ISSUE TITLE
angular esri-loader 4.18 graphics refresh bug

### ISSUE THREAD

**Issue by MakiG007** [Esri/esri-loader#263]
This Stack Blitz best showcases the issue: [https://stackblitz.com/edit/angular-esri-loader-graphics-layer-bug?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-esri-loader-graphics-layer-bug?file=src/app/app.component.ts)

### Expected behavior

- Add a graphic to the map, it should appear without requiring the user to zoom in/out
- Latest Angular, esri-loader

### Actual behavior

- With esri js api version 4.18, the graphics do not appear until the user zooms in/out

### Steps to reproduce the behavior

1. [https://stackblitz.com/edit/angular-esri-loader-graphics-layer-bug?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-esri-loader-graphics-layer-bug?file=src/app/app.component.ts)
2. Click the "Load Map 4.18" button
3. Note that the graphics do not appear until you zoom in/out

**Comment by andygup** [comment]
@MakiG007 thanks for reporting. This is a known issue that we are looking into. 

Reference: https://github.com/Esri/jsapi-resources/issues/268

**Comment by andygup** [comment]
@MakiG007 we've believe we've fixed this bug. Please retest using `npm install @arcgis/core@next`

**Comment by MakiG007** [comment]
@andygup confirmed, thanks, this appears to resolve the issues

**Comment by andygup** [comment]
Awesome, thanks for confirming. The fix will officially go out in the early April 4.19 production release.
