### ISSUE TITLE
new `esri-loader-typings-helper` plugin for VS Code

### ISSUE THREAD

**Issue by CalebM1987** [Esri/esri-loader#266]
I do not really know where to advertise this, but I just built a handy [new extension](https://marketplace.visualstudio.com/items?itemName=CalebMackey.esri-loader-typings-helper) called `esri-loader-typings-helper` for VS Code to autogenerate the `loadModules()` syntax with JavaScript and TypeScript support.  To use, simple write a list of modules to import, select the text and run the plugin:

```js
["esri/Map", "esri/views/MapView", "esri/layers/FeatureLayer", "esri/config"]
```

Here is a preview of it in action:
![plugin-async](https://user-images.githubusercontent.com/6826046/111081973-e16e4c00-84d3-11eb-87c1-00cffb7550c9.gif)

It will support both the `async/await` pattern as well as using a `promise`:
![plugin-promise](https://user-images.githubusercontent.com/6826046/111082011-1aa6bc00-84d4-11eb-936c-c1ffea8ae5cf.gif)

When used in JavaScript, it behaves the same except excludes the typings for the appropriate constructors:
![plugin-async-js](https://user-images.githubusercontent.com/6826046/111082145-c223ee80-84d4-11eb-8fb5-a5087a08f209.gif)

If you guys think this is worth mentioning in the `README`, feel free to advertise it. Otherwise, kindly ignore this enhancement request.  The Github repo can be found [here](https://github.com/CalebM1987/esri-loader-typings-helper) for anyone who is interested in contributing/improving.

**Comment by tomwayson** [comment]
This is awesome.

This is definitely worth including in the README. To me it fits well under the [Advanced Usage](https://github.com/Esri/esri-loader#advanced-usage) section. I would gladly accept a PR for that.

**Comment by CalebM1987** [comment]
Thanks @tomwayson. 

I will create a PR that includes some quick info on it in the Advanced Usage section.
