### ISSUE TITLE
ERROR    ReferenceError: Can't find variable: document

### ISSUE THREAD

**Issue by midhungopipk** [Esri/esri-loader#294]
@Esri, @EsriGithub
@glazou, @davidgalindo

[Thu May 12 2022 17:51:09.777]  ERROR    ReferenceError: Can't find variable: document

This error is located at:
    in EsriMap (at MapScreen.js:109)
    in RCTView (at View.js:34)
    in View (at MapScreen.js:107)
    in MapScreen (at SceneView.tsx:132)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:125)
    in EnsureSingleNavigator (at SceneView.tsx:124)
    in SceneView (at useDescriptors.tsx:217)
    in RCTView (at View.js:34)...........

I'm trying to implement ArcGIS map in react native.....and i have found this, implementing map using esri-loader....then i finish creating a component as shown in documentation...and i get this error. any one know how to solve this???

is it possible to integrate ArcGIS map in a react native app? Can any one kindly explain me how to implement it

**Comment by andygup** [comment]
@midhungopipk we don't support using the ArcGIS API for JavaScript with react native. If you do some internet searching you can find some unsupported examples.

**Comment by andygup** [comment]
Closing.
