### ISSUE TITLE
Update product name in error messages at 4.26

### ISSUE THREAD

**Issue by andygup** [Esri/esri-loader#303]
Reference https://github.com/Esri/esri-loader/pull/302

**Comment by arvinthvikas** [comment]
hey hi i want change the default map language ,kindly help me

**Comment by andygup** [comment]
Hi @arvinthvikas for general SDK functionality questions please post them on the Community site: https://community.esri.com/t5/arcgis-javascript-maps-sdk-questions/bd-p/arcgis-api-for-javascript-questions

**Comment by andygup** [comment]
Closing.
