### ISSUE TITLE
What is the latest version that supports Angular 14 and ESRI JS API v3.x?

### ISSUE THREAD

**Issue by zjzou** [Esri/esri-loader#308]
This is not to report an issue but a question. About 5-6 years ago, we developed a web app with Angular 5 and esri-loader 2.2.0. Now after upgrading Angular to version 14, esri-loader seems not being loaded. Migrating to ES modules and ArcGIS JS API v4.x will take significant amount of effort, and hard to justify it for a project working well for the past 5 years. 

What is the latest version of esri-loader that can support Angular 14 and ArcGIS JS API v3.x?

Thanks,
Jason Zou

**Comment by andygup** [comment]
Hi @zjzou you should definitely look into migrating from 3.x to 4.x. The 3.x SDK will be retired on July 1, 2024, for more info see this [blog post](https://www.esri.com/arcgis-blog/products/js-api-arcgis/developers/arcgis-api-for-javascript-version-3-x-retirement/).

> What is the latest version of esri-loader that can support Angular 14 and ArcGIS JS API v3.x?

I'm not sure. [Angular 14](https://angular.io/guide/releases#actively-supported-versions) is in Long Term Support, and that ends in November 2023.

**Comment by andygup** [comment]
Closing. Please let us know if you have additional queestions.
