### ISSUE TITLE
How to change the default  Map Language ?

### ISSUE THREAD

**Issue by arvinthvikas** [Esri/esri-loader#312]
### Expected behavior

- Describe what you expected or wanted to happen.
- What you are trying to achieve?
- Describe your environment/framework and be specific with version numbers (e.g. React 16.2, react-router 4.2, redux 3.7, node 8.3).

### Actual behavior

- Describe what occurs in your code.
- Specifically, what seems to work differently than you intended?
- Provide any error messages you see in the console.

### Steps to reproduce the behavior

**We can only help you if we're able to easily reproduce the behavior you describe above.**

Please provide:

1. Steps to reproduce the behavior.
2. A link to an app where we can carry out those steps and see the source code.

To help you reproduce issues in an environment that we can't access (e.g. private repository) follow these helpful tips:

- If the problem is related to the ArcGIS Maps SDK for JavaScript (i.e. behavior of the map, etc), start here https://github.com/Esri/esri-loader#without-a-module-bundler.
- Otherwise, search for and fork a codesandbox that is similar to your environment (React, etc): https://codesandbox.io/search
  - For sandboxes that depend on esri-loader see: https://codesandbox.io/search?refinementList[npm_dependencies.dependency][0]=esri-loader

**Comment by andygup** [comment]
Thanks for reaching out, for ArcGIS JS SDK functionality questions please open an issue on the Esri Community site: https://community.esri.com/t5/arcgis-javascript-maps-sdk-questions/bd-p/arcgis-api-for-javascript-questions. I'm going to close out this issue since it's not related to esri-loader.
