### ISSUE TITLE
Update for JSAPI 4.5 and 3.22

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#33]
Default to 4.5

Show 4.5 and 3.22 in docs.

**Comment by ziveo** [comment]
I figure out what is going on.
This is my first time setting up fork syncing for a project.

Let me know if everything is working good now.

Thanks

**Comment by tomwayson** [comment]
TODO:
- [ ] new release

**Comment by tomwayson** [comment]
Sorry for the delayed release, there was a mismatch btwn git tags, CHANGELOG, and npm versions. I finally had the time to sort that out. v1.2.0 is now published.
