### ISSUE TITLE
WebGL?

### ISSUE THREAD

**Issue by CraigglesO** [Esri/esri-loader#35]
Is there a way to make sure to add:

```
<script>
  var dojoConfig = {
    has: {
      "esri-featurelayer-webgl": 1
    }
  };
</script>
```

(^^^^^ from the docs)
It would be nice to have improved performance of vector drawings.

**Comment by CraigglesO** [comment]
Actually, this might be a better question for `esri-loader-react` as it is a really great lazy loader...

**Comment by tomwayson** [comment]
https://github.com/davetimmins/esri-loader-react/issues/3#issuecomment-334885235
