### ISSUE TITLE
Make `getScript()` a public API?

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#44]
Why not?

Also, [this change](https://github.com/Esri/esri-loader/pull/22/files#diff-2a8ec81f6d45eb44dd396b4707a24fceL9) has always bothered me a bit. I think `isLoaded()` should not be concerned with how the script tag was added to the page. Making `getScript()` a public API would pave the way to revert that change (at the next major release) b/c consumers could just call `isLoaded() && getScript()` if needed.

cc @TheKeithStewart

**Comment by TheKeithStewart** [comment]
Makes sense. Sounds good to me, @tomwayson.
