### ISSUE TITLE
Preloading a specific versions of the JSAPI forces consumers to pass same url to loadModules()

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#51]
Kind of an edge case here, but if you pass a specific JSAPI version when preloading (i.e. `loadScript({ url: 'https://js.arcgis.com/3.22' })`) then you have to make sure that subsequent calls to `loadModules()` include that same `url` option. If you don't, and the JSAPI hasn't loaded by the time `loadModules()` is called, it will try to lazy load the default version (latest 4.x) and it will reject with an error.

One solution is to just document the above.

Another idea would be to cache url that it's attempting to load the first time `loadScript()` is called and then default to that (instead of latest 4.x) for subsequent calls - either at the `loadModules()` or `loadScript()` level.

**Comment by leqwasd** [comment]
And also loadScript includes this
```
        if (options.dojoConfig) {
          // set dojo configuration parameters before loading the script
          window['dojoConfig'] = options.dojoConfig;
        }
```
which could be dangerous - you can break the app, by changing default dojoConfig or dojoConfig, that was set before with loadScript. I would suggest - a factory for whole ersi-loader, which would return new esri-loader with user configured defaults, urls and dojoConfigs

**Comment by tomwayson** [comment]
> you can break the app, by changing default dojoConfig or dojoConfig, that was set before with loadScript. 

thanks @leqwasd - but that only executes [if the JSAPI is not loaded (i.e. `window.require()` is not defined) _and_ we're not currently in the process of loading the script (i.e. the script tag does not exist)](https://github.com/Esri/esri-loader/blob/8dc3b0219c99c3c6d4291ba9dbe3a5e245b42274/src/esri-loader.ts#L128), so I don't think that will be a problem.

#66 is the solution that I'm currently proposing for this problem. I would appreciate your feedback on that.
