### ISSUE TITLE
IE11: "TypeError: Object doesn't support this action"

### ISSUE THREAD

**Issue by dtsao** [Esri/esri-loader#53]
I switched from `esriLoader.bootstrap` and `esriLoader.dojoRequire` to `esriLoader.loadModules` in my Vue.js app using jsapi 3.20. This is working fine in Chrome, but IE11 gives the error above.

I've tried these promise polyfills, with the same results: `"promise-polyfill": "^6.0.2"` and `"es6-promise": "^4.1.1"` and verified that window.Promise exists.

I also tried adding a script tag to my index.html:
```
<script src="https://js.arcgis.com/3.20/" data-esri-loader="loaded"></script>
```
but I get the same result.

Any ideas?

![11-17-2017 3-39-21 pm](https://user-images.githubusercontent.com/4969981/32968023-bf6d4e22-cbad-11e7-95d3-c6550a6df7d9.png)

**Comment by tomwayson** [comment]
Can you show index.html code, specifically to verify that the Promise polyfill is loaded _before_ `loadModules` is called. I above that see you log `window.Promise` _after_ that call fails.

**Comment by dtsao** [comment]
Thanks for your reply. I'm loading the promise polyfill in App.vue (my root vue component):

```
<script>
  import Spinner from 'vue-simple-spinner';
  import StratFilter from './components/StratFilter';
  import ViewButtons from './components/ViewButtons';
  import TableView from './components/TableView';
  import MapViewContainer from './components/MapViewContainer';
  import helper from './helper';
  import eventBus from './event-bus';

  require('es6-promise/auto'); // for IE11 when use Axios
  require('es6-object-assign/auto'); // for IE11 when use vue-js-modal

  const axios = require('axios');

  const _ = require('lodash');

```
window.Promise is present before calling esriLoader.loadModules:
![11-18-2017 10-37-32 am](https://user-images.githubusercontent.com/4969981/32982283-16f3e73a-cc50-11e7-8a62-3c31fd117dbd.png)

More debug info:
Exception is on line 85 in loadScript:
![11-18-2017 10-52-06 am](https://user-images.githubusercontent.com/4969981/32982234-0cdbd704-cc4f-11e7-80d4-4b6ba47f58b0.png)

called from line 158 in loadModules:
![11-18-2017 10-53-04 am](https://user-images.githubusercontent.com/4969981/32982235-11782bd2-cc4f-11e7-8a91-9befb014955e.png)

called from my call to loadModules:
![11-18-2017 10-53-51 am](https://user-images.githubusercontent.com/4969981/32982236-15029a62-cc4f-11e7-83af-443d78affa77.png)

**Comment by dtsao** [comment]
I got it working. The error was occurring because `utils.Promise` is undefined:

![11-18-2017 11-06-11 am](https://user-images.githubusercontent.com/4969981/32982334-b0de4138-cc50-11e7-821f-1d18890eadce.png)

I fixed the error by assigning window.Promise to esriLoader.utils.Promise. Should the readme be changed to say this is required when using a promise polyfill?

```
  // added this line to fix IE11 error: TypeError: Object doesn't support this action
  esriLoader.utils.Promise = window.Promise;

  esriLoader.loadModules([
  ...

```

After this change, the maps are loading in IE11, Chrome, and FF.

**Comment by tomwayson** [comment]
@dtsao 

I'm glad you got it working, but you shouldn't _have_ to add that line when using a polyfill.

The `utils.Promise` is `undefined` error indicates that your promise polyfill is **not** loaded when the esri-loader library (i.e. esriLoader.js) is loaded. Generally, if you're going to use a polyfill, it needs to be added to the page _before_ any other library (vue, esri-loader, etc).

The alternative is to use a promise _library_ (not a polyfill) and after that loads you can set `esriLoader.utils.Promise`. So:

```js
import Promise from 'my/favorite/promise/lib';

// before using esri-loader, tell it to use the promise library
esriLoader.utils.Promise = Promise;
esriLoader.loadModules([
  ...
```

**Comment by dtsao** [comment]
@tomwayson 
Thanks for the clarification. I changed my code to load my polyfills before loading the vue library by moving these lines from App.vue to main.js:
```
import 'es6-promise/auto'; // for IE11 when use Axios and esri-loader
import 'es6-object-assign/auto'; // for IE11 when use vue-js-modal
```
With this change, esriModule.loadModules` now works in IE11, Chrome, and FF without needing this line of code:
```
esriLoader.utils.Promise = window.Promise;
```
