### ISSUE TITLE
`script.dataset` is not compatible with ie10

### ISSUE THREAD

**Issue by fifman** [Esri/esri-loader#60]
With esriLoader, ie 10 reported the following error:

TypeError, unable to set property 'esriLoader' of undefined or null reference

Then I found that the value of `script.dataset` is `undefined` in IE10. After I moved the source out and deleted all the sentences where `script.dataset` is used, everything worked fine. #

**Comment by tomwayson** [comment]
Thank you.

I had been thinking that this library should only support IE11, b/c that is what is [supported by v4.x of the JSAPI](https://developers.arcgis.com/javascript/latest/guide/system-requirements/index.html#supported-browsers).

However, I forgot that [v3.x supports IE9+](https://developers.arcgis.com/javascript/3/jshelp/supported_browsers.html).

I will not be possible for this library to support IE<11 w/o a contributor that is dedicated to the related changes and maintenance. I personally have no intentions of supporting it.

The README should be updated to reflect that.

**Comment by tomwayson** [comment]
@fifman this should be fixed as of v1.6.1
