### ISSUE TITLE
loadScript should return a singleton promise, or DEFAUL_URL should be configurable library-wise 

### ISSUE THREAD

**Issue by veonline** [Esri/esri-loader#61]
I've a probelm in my vuejs app due to the async nature of loadScript and loadModules.
When i boot my vue app i bootstrap also the esri library with `loadScript({ url: "https://js.arcgis.com/3.22/init.js"})` and in some of my vue components i load modules with something like `loadModules(['esri/geometry/geometryEngine'])`
If loadScript with the custom version of the library is not completed, loadModules is rejected.
The solution is to provide the same promise instance for every loadScript call or maybe provide a configurable DEFAULT_URL or seti it with the first call of loadScript.

**Comment by tomwayson** [comment]
Thanks @veonline 

This is the same problem that I mention in #51.

As mentioned in that issue, a work around for now is to pass the same options  to `loadModules()`, so:

```js
loadModules(['esri/geometry/geometryEngine'], { url: "https://js.arcgis.com/3.22/init.js"})
```

I've elevated the priority of these issues.
