### ISSUE TITLE
Does this work w/ Parcel?

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#72]
[parcel](https://parceljs.org/) is the latest, no-config, module bundler.

I bet esri-loader works just fine in parcel, or at least better than the ["exclude and require" approach](http://tomwayson.com/2016/11/27/using-the-arcgis-api-for-javascript-in-applications-built-with-webpack/) given that [parcel doesn't seem to currently support marking modules as external](https://github.com/parcel-bundler/parcel/issues/144).

I'd love to see an example using esri-loader in a parcel app, so let me know if you've got one. If one doesn't materialize by DevSummit, I'll probably whip one up using one of the many [React](https://www.google.com/search?q=react+parcel&oq=react+parcel) or [Preact](https://www.google.com/search?q=preact-starter+parcel) parcel boilerplates.

**Comment by tomwayson** [comment]
... or [FuseBox](https://medium.com/fusebox/fusebox-3-0-faster-than-ever-5fae4254556c)

**Comment by tomwayson** [comment]
... or [steal.js](https://stealjs.com/)

See https://github.com/roemhildtg/can-arcgis/issues/10

**Comment by jwasilgeo** [comment]
I've got something brewing that I want to try with Parcel.  Y'all can expect my report in the coming hours/days.

**Comment by jwasilgeo** [comment]
As it turns out, Parcel works like a charm and esri-loader fits right in without a problem.  Here's one way to wire it up: https://github.com/jwasilgeo/esri-hyperapp-example

**Comment by tomwayson** [comment]
Well that settles that. I'm going to close this feeling pretty confident that this will work in FuseBox or whatever comes next.
