### ISSUE TITLE
document API

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#74]
Either add section to README by hand, or automate  with something like https://github.com/TypeStrong/typedoc

If the latter, where to host the output? gh-pages? I think we'll want something more than just API docs there, like a lot of what's in the README. Then how to keep those in sync?

**Comment by tomwayson** [comment]
This was partially completed in #196.

**Comment by andygup** [comment]
Closing since this package is scheduled for deprecation at 4.29.
