### ISSUE TITLE
Update Examples

### ISSUE THREAD

**Issue by tomwayson** [Esri/esri-loader#76]
Add: 
- https://github.com/nicksenger/esri-promise
- https://github.com/odoe/vue-jsapi4

Also break each section into reusable libraries vs example applications.

**Comment by andygup** [comment]
Yah, it can have it's own section, that works. 👍

**Comment by tomwayson** [comment]
Here's another idea, provide a link to questions people have asked for each framework like: 
https://github.com/Esri/esri-loader/issues?utf8=%E2%9C%93&q=label%3Aquestion

**Comment by andygup** [comment]
>>provide a link to questions people have asked for each framework like...

I have mixed thoughts on this. Do we want to emphasize that framework-specific questions generally should go to those respective github repos? Or do we want this repo to be a catch-all? I'm leaning towards the first approach. Just some food for thought

**Comment by tomwayson** [comment]
Good point @andygup - I just punted on that for now and left it out of #79
