### ISSUE TITLE
cant configure dojoConfig 

### ISSUE THREAD

**Issue by alekssilver** [Esri/esri-loader#96]
i am trying to pass dojoConfig with following value
esriLoader.loadScript({
url: 'https://js.arcgis.com/4.6/',
dojoConfig: {
has: {
"esri-featurelayer-webgl": 1
}
}
but it seems that WebGL is not configured as need

**Comment by davetimmins** [comment]
You need to wrap it in an options parameter e.g.options { dojoConfig

**Comment by alekssilver** [comment]
not sure what do you mean. if you look at my code, you can see that i do so. I pass options as 
{
url: 'https://js.arcgis.com/4.6/',
dojoConfig: { has: {
                           "esri-featurelayer-webgl": 1
                              }
                     }
}

so what is wrong there?

**Comment by alekssilver** [comment]
in javascript it should be so

<script>
   var dojoConfig = {
   has: {
   "esri-featurelayer-webgl": 1
   }
   }
</script>
i am just not sure how to pass this via 'esri-loader'

**Comment by davetimmins** [comment]
Wrap ii in another object. dojoConfig should be a property of the options

**Comment by alekssilver** [comment]
Yes. It is so. dojoConfig is property of options. 
var options = {
      url: 'https://js.arcgis.com/4.6/',
      dojoConfig: {
        has: {
          "esri-featurelayer-webgl": 1
        }
      }
    }
esriLoader.loadScript(options)

Am i right?

**Comment by davetimmins** [comment]
Have a look here, that code passes the config through (on my phone sorry do hard to tell what you're asking) https://github.com/davetimmins/arcgis-react-redux-legend/blob/master/demo/src/index.js

**Comment by alekssilver** [comment]
thanks for answer. but i do so. my code is as same as in your example. 
    var options = {
      url: 'https://js.arcgis.com/4.6/',
      dojoConfig: { has: { "esri-featurelayer-webgl": 1 } }
    }

is it correct code? right?

**Comment by davetimmins** [comment]
Yeah so in that case what is the problem you're seeing?

**Comment by alekssilver** [comment]
i am trying to turn on WebGL rendering for feature layers . if you look at documentation all that needs is to preconfigure dojo https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#webgl-rendering
but it looks that WebGL-rendering is not working.  So not sure where is problem.

**Comment by davetimmins** [comment]
What is happening to make you think it isn't working? Any errors in the console? Or some other symptoms? Also where is the feature layer hosted ?

**Comment by alekssilver** [comment]
i do not see that it works faster. some functions do not work. for example , function FeatureLayerView.highlight() is not working https://developers.arcgis.com/javascript/latest/api-reference/esri-views-layers-FeatureLayerView.html#highlight

**Comment by davetimmins** [comment]
It looks to me like it renders differently, though the highlight function probably only works in certain scenarios which is more of a limitation with the 2D rendering of the Esri JS API than this lib. Are you able to get a repro with the highlight working just using something like jsfiddle as  then it would be easier to test if it doesn't work using esri-loader. First image is with the option, second is without.

![with](https://user-images.githubusercontent.com/1118347/36782170-f5c0ea6c-1cdc-11e8-9f31-950bba15c756.PNG)
![without](https://user-images.githubusercontent.com/1118347/36782174-f89fd6c6-1cdc-11e8-81ac-b788c88c15b8.PNG)

**Comment by alekssilver** [comment]
ok. i checked my feature service with simple java script . added dojoConfig as need. It does not work with WebGL on 2d map. Not sure why. We use latest verision of ArcGis Server 10.6 . So it looks that problem is not 'esri-loader'

**Comment by jwasilgeo** [comment]
When you mentioned ArcGIS Server 10.6 it made me curious about the known limitations at JSAPI 4.6 for what you're trying to do.  Are you sure that all the requirements/caveats are met here under the section "Known Limitations"?

https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#webgl-rendering

> "Currently, support is limited to layers created from feature services hosted on ArcGIS Online. Non-hosted enterprise feature services will be supported at the ArcGIS Server 10.6.1 release."

**Comment by jwasilgeo** [comment]
If any other `dojoConfig` options are being properly set in your application, then we should rule out esri-loader and assume that this is either a known limitation situation with the current JSAPI and Server version you are using.

**Comment by alekssilver** [comment]
It looks that i need to wait 10.6.1 release. Because feauter service is not hosted on ArcGis Online. Right?

**Comment by jwasilgeo** [comment]
Yes, I would agree with that.  I'll close this for now but feel free to let us know if you have any subsequent esri-loader issues or questions.
