### ISSUE TITLE
Remote esri-loader script 404

### ISSUE THREAD

**Issue by nbumbarger** [Esri/esri-loader#99]
### Expected behavior
- Script is able to initialize by fetching from https://js.arcgis.com/4.6/dojo/esri-loader.js

### Actual behavior
- Dojo loader reports a path not found error. The path https://js.arcgis.com/4.6/dojo/esri-loader.js resolves to a 404.
![image](https://user-images.githubusercontent.com/9471488/37668151-255b5886-2c3a-11e8-9e2a-8e3b3ef80d5c.png)

### Steps to reproduce the behavior
Attempt to use the loader or visit https://js.arcgis.com/4.6/dojo/esri-loader.js.

**Comment by andygup** [comment]
Can you provide a codepen, jsbin, or a code snippet of how you are implementing this?

**Comment by tomwayson** [comment]
> Script is able to initialize by fetching from js.arcgis.com/4.6/dojo/esri-loader.js

esri-loader is not hosted w/ the JSAPI. That URL is invalid. What do you mean by "initialize", do you mean adding a `<script>` tag to the page that pulls esri-loader  from a CDN? If so, use this URL: https://unpkg.com/esri-loader 

If you mean supplying the `url` option to `loadModules()` or `loadScript()` you should just pass the base URL of the ArcGIS API for JavaScript:  `url: 'url: 'https://js.arcgis.com/4.6'`.

**Comment by tomwayson** [comment]
I suspect that your webpack config is still configured to treat any module that starts w/ 'esri' as `external` like [this](https://github.com/Esri/react-redux-js4/blob/master/webpack.config.babel.js#L24) and to output the bundle as an AMD module like [this](https://github.com/Esri/react-redux-js4/blob/master/webpack.config.babel.js#L17). esri-loader is an _alternative_ to that method. You need to remove those configurations and make sure that the ArcGIS API is not loaded some other way (like having a `<script>` tag in index.html).

**Comment by andygup** [comment]
Closing. Feel free to reopen if you have additional questions/issues.
